### ISSUE TITLE
Errno::EMFILE: Too many open files - pipe

### ISSUE THREAD

**Issue by blanchma** [httprb/http#165]
Case:
Running several times a class which do http requests:

class SmsService
include Celluloid::IO

def initialize
...
end

def deliver
response = HaHelper::HTTP.get(url, ssl_socket_class: Celluloid::IO::SSLSocket).to_s
end
end

Environment:
rvm use 1.9.3-p484

celluloid (0.16.0)
celluloid-io (0.16.1)
http (0.6.2)
Stacktrace:

Celluloid::PoolManager: async call perform aborted!
Errno::EMFILE: Too many open files - pipe
/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-io-0.16.1/lib/celluloid/io/reactor.rb:16:in new' /Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-io-0.16.1/lib/celluloid/io/reactor.rb:16:ininitialize'
/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/evented_mailbox.rb:9:in new' /Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/evented_mailbox.rb:9:ininitialize'
/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-io-0.16.1/lib/celluloid/io/mailbox.rb:6:in initialize' /Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/actor.rb:105:innew'
/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/actor.rb:105:in initialize' /Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/cell.rb:21:innew'
/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/cell.rb:21:in initialize' /Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid.rb:168:innew'
/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid.rb:168:in new' /Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/http-0.6.2/lib/http/chainable.rb:140:inbranch'
/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/http-0.6.2/lib/http/chainable.rb:52:in request' /Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/http-0.6.2/lib/http/chainable.rb:12:inget'
/Users/blanchma/workspace/applicationservice/app/services/sms_service.rb:49:in `deliver'

**Comment by kamui** [comment]
I'm having a similar problem here. I'm using http.rb with celluloid-io in Rails (with unicorn) and the file descriptors don't seem to free until I end the unicorn process. Each request just creates new ones and the number of file descriptors only accumulates until I read my limit.

**Comment by kamui** [comment]
Nevermind, I figured it out. I read the celluloid docs and added calls to `#terminate` on each actor was done. Without terminate each actor it would just create new actors and not clean up old ones every time a new request came in.
