### ISSUE TITLE
Provide high-level API to wire Celluloid::IO (socket classes, timeouts)

### ISSUE THREAD

**Issue by ixti** [httprb/http#204]
See: https://github.com/httprb/http.rb/issues/203#issuecomment-90156883

``` ruby
HTTP.backend(:celluloid)
```

**Comment by ixti** [comment]
I dislike name of the method actually, and propose to name it `celluloid` :D

``` ruby
HTTP.celluloid # => Celluloid-ready configured client 
```

**Comment by sferik** [comment]
For what it’s worth, I prefer your original suggestion. Hard-coding Celluloid configuration to a top-level method name limits the extensibility of this library.

**Comment by ixti** [comment]
@sferik `#backend` was actually Tony's proposal :)) I was thinking about sortening that to `#use` or `#with`, but after thinking on exisitng chainable API  though that adding `#celluloid` into `Chainable` module will be a good idea.

Anyway, I agree that hard-coding celluloid config as a top-level method is not a good idea after all.

**Comment by sferik** [comment]
:+1: for `#use` or `#width`. My biggest objection to hardcoding `#celluloid` is that it wouldn’t be easily extensible to alternate configurations without monkey patching the `HTTP` object, which could result in method name collisions.

**Comment by sferik** [comment]
:-1: for `#with`, since that used to be an alias for `#with_headers`. IMHO, changing the API in this way would create confusion.

**Comment by tarcieri** [comment]
`#use` seems good to me

**Comment by zanker** [comment]
+1 on use, can we deprecate the old Api in 1.0 too? Could make config a lot easier

**Comment by ixti** [comment]
I would like not to deprecate but completely drop out any things we want to deprecate. :D

**Comment by tarcieri** [comment]
Celluloid support is effectively dropped in 1.0. It's something we can revive, but it requires work in the timeouts backend (which should probably be extracted into a [separate gem](https://github.com/zanker/socketry))
