### ISSUE TITLE
Determine string encoding based on Content-Type

### ISSUE THREAD

**Issue by ixti** [httprb/http#224]
See discussion: https://github.com/httprb/http.rb/commit/1ab394f06da8b0ce5b9e26b21e07460351677277#commitcomment-11136186

**Comment by Connorhd** [comment]
I did look into this briefly (before realizing it was more complicated than a quick fix). Couple of things I found https://github.com/mime-types/ruby-mime-types/ has a `binary?` method on mimetypes that could be useful. And https://github.com/jmhodges/rchardet exists to detect character encoding the same way browsers do.

**Comment by ixti** [comment]
I love both gems. But would like to avoid having dependency, and definitely against having `rchardet` as default resolution algorithm (it's pretty heavy). Probably this should be done like pluggable extensions to body streamer.

In any case I'm removing this from any milestone. This will not introduce (most likely) any backward compatible changes so it can be implemented whenever it's possible. So if somebody will implement this - will be happy to review PR.

**Comment by tarcieri** [comment]
We merged #234
