### ISSUE TITLE
Celluloid Timeout Support

### ISSUE THREAD

**Issue by aronchick** [httprb/http#225]
I know that current Celluloid Timeouts are currently not supported, but is there an interim workaround?

Here's the code I'd _like_ to run:
```
  def fetch(url, options = {} )
    puts "Request -> #{url}"
    begin
      options = options.merge({ socket_class: Celluloid::IO::TCPSocket,
                                timeout_class: HTTP::Timeout::Global,
                                timeout_options: {
                                  connect_timeout: 1,
                                  read_timeout: 1,
                                  write_timeout: 1
                                  }
                              })
      HTTP.get(url, options)
    rescue HTTP::TimeoutError => e
      [do more stuff]
    rescue Exception => e
      puts e
    end
  end
```

Its goal is to test a server as being live and healthy.

**Comment by zanker** [comment]
Set `options = options.merge(socket_class: Celluloid::IO::TCPSocket, timeout_class: HTTP::Timeout::Null)` should work, as it bypasses the timeout code.

**Comment by aronchick** [comment]
Interesting! Can we call that with different values?

**Comment by zanker** [comment]
Which part with different values? Not quite sure what you mean.

**Comment by aronchick** [comment]
Sorry, I was hoping to have the ability to set a timeout at 1s for some
requests, and 20s for other requests. Is that variable?

**Comment by zanker** [comment]
If you aren't using Celluloid IO, you can change it to whatever you want, but we don't support timeouts when using Celluloid IO right now.

**Comment by aronchick** [comment]
I guess that's my issue - I'm using Celluloid IO - is there an alternative
for Timeouts?

**Comment by zanker** [comment]
I'm not familiar enough with Celluloid IO to offer a suggestion, sorry.

**Comment by tarcieri** [comment]
Closing this. Please continue discussion in #272
