### ISSUE TITLE
Data read fails.

### ISSUE THREAD

**Issue by ixti** [httprb/http#248]
Example request that constantly fail with `EOFError`:

``` ruby
HTTP.accept(:json).get("http://github.com/").to_s
HTTP.get("https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=foobar").to_s
```

Failure happens after headers were read. Thus `to_s` is essential here.
Regression was introduced by: https://github.com/httprb/http/commit/65900ad36e2ec47b1e1c5dce2e801fdf21637a8b

**Comment by ixti** [comment]
As far as I can see ruby can raise EOFError even if you passed `exception: false`, e.g.: https://github.com/ruby/ruby/blob/ruby_2_1/ext/openssl/lib/openssl/buffering.rb#L189

**Comment by zanker** [comment]
:|

**Comment by zanker** [comment]
I'll fix it in http.rb but I want to get a PR into openssl too and actually fix it properly

**Comment by zanker** [comment]
Actually wait no, that's not a regression from that commit, it's a regression from timeouts. 

That openssl code looks like it could never actually trigger.

**Comment by ixti** [comment]
Well, probably I have pointed out wrong commit, indeed, it was just lack of that rescue block so I said so :D I could be wrong, indeed. Was also fixing that, but was slower on pushing the fix ;)) My patch looked (rejected in favor of your fix) like this:

``` diff
diff --git a/lib/http/connection.rb b/lib/http/connection.rb
index 7daeed3..a01785f 100644
--- a/lib/http/connection.rb
+++ b/lib/http/connection.rb
@@ -207,12 +207,15 @@ module HTTP
     def read_more(size)
       return if @parser.finished?
 
-      value = @socket.readpartial(size)
-      if value == :eof
-        :eof
-      elsif value
-        @parser << value
+      begin
+        value = @socket.readpartial(size)
+      rescue EOFError
+        return :eof
       end
+
+      return :eof if value == :eof
+
+      @parser << value
     end
   end
 end
```
