### ISSUE TITLE
Refactor timeouts and move them into separate gem

### ISSUE THREAD

**Issue by ixti** [httprb/http#249]
Subj

**Comment by zanker** [comment]
I would disagree with this, just because timeouts are a core part of a HTTP library, and trying to separate them out is likely to make it even harder to test changes and keep things in sync.

**Comment by tarcieri** [comment]
@zanker needs more socketry :open_mouth:

**Comment by zanker** [comment]
So little time :(

**Comment by tarcieri** [comment]
Will track this going forward in #272
