### ISSUE TITLE
ActiveSupport dependency is missing

### ISSUE THREAD

**Issue by Fryie** [httprb/http#253]
The gem seems to use ActiveSupport methods in some places, e.g. [here](https://github.com/httprb/http/blob/master/lib/http/request/writer.rb#L90). In order to be compatible with non-Rails projects, the dependency should be included and the appropriate libraries required where necessary (should be detailed [here](http://guides.rubyonrails.org/active_support_core_extensions.html)).

**Comment by tarcieri** [comment]
That's a PR that just landed (#251). It's not intended for this gem to depend on ActiveSupport.

**Comment by tarcieri** [comment]
@zanker are the tests actually exercising that case? I'm surprised they didn't break

**Comment by tarcieri** [comment]
It looks like the `certificate_authority` gem pulls in `activesupport`. Perhaps we should get rid of it.

**Comment by Fryie** [comment]
Oh, I see. In the meantime, I guess `!data.empty?` would fix the issue since it's probably always a string?

**Comment by tarcieri** [comment]
PR here: https://github.com/httprb/http/pull/254

**Comment by tarcieri** [comment]
This is now released as 0.9.6

**Comment by Fryie** [comment]
This must be some of the quickest feedback i've seen on a library. :) thanks.
