### ISSUE TITLE
When using HTTP.persistent, cookies are not preserved

### ISSUE THREAD

**Issue by ook** [httprb/http#263]
Context:
I'm doing request against an site that attributes a cookie to keep a session. All requests are done with a `HTTP.persistent(HOST)` call.

Problem:
Each time I make a request, I get a new session cookie.

Expected behavior:
The session cookie doesn't change between two calls.

Here a gist let you test it: https://gist.github.com/ook/d054e3878376da4b40b6

**Comment by oz** [comment]
This would be nice. :+1:

I found something similar today while using the redirector (`HTTP.follow.get("...")`): there is no option to *reuse* a cookie jar between a chain of redirects to the same domain (e.g. NY Times).

There's probably some shared behavior with persistent connections handling, but I'm not sure what the API should be. :sweat:

**Comment by tarcieri** [comment]
This seems useful. I am sticking it in the `2.0` milestone for now, but I could see it as a `1.1` feature

**Comment by ixti** [comment]
`HTTP.persistent` is about persistent connection. It's not about session handling.
Having session management is pretty awesome idea, though. But it will be separate API call IMO.

@oz that's a good catch. But it's a separate issue.

**Comment by ixti** [comment]
After filling an issue #264 I realized that actually these two are closely related.

**Comment by ixti** [comment]
After thinking on this a little bit more, I realized that it's a bit more of work than I initially thought.
So, here's example code:

``` ruby
res = HTTP.get(auth_uri, :params => { :username => user, :password => pass }).flush
fail "not logged in" unless res.ok?
pp HTTP.cookies(res.cookies).get(profile_uri).parse
```

Tricky part is `#cookies(...)` call. Which returns new client.
Obviously it won't play nice with current logic of persistent connections.
That also brings me to another conclusion, we need to fix this defect anyway.
Consider following code:

``` ruby
HTTP.persistent "https://example.com" do |http|
  http.get("/foo") # all good
  http.post("/bar") # good again. connection re-use

  # here comes the pain...
  http.headers("X-Foo" => "Bar").get("/foo")
end
```

So, most likely we need a way to "pass" underlying connection to new client.

**Comment by tarcieri** [comment]
Yes, this can also be problematic in a lot of cases, like if you're using a connection pool shared across threads

**Comment by ook** [comment]
Why not having a `Cookie::Jar` instanciates in `Http.persistent`, just before yielding, and Response and Request instances passing that reference between each request (just by checking persistent context) ?

**Comment by ixti** [comment]
@ook all (more or less) `persistent` does is keeping connection open.
HTTP is stateless protocol. With that being said, you can for example have 2 different sessions within single connection:

``` ruby
HTTP.persistent host do |http|
  admin = http.post(auth_url, :params => { :user => "admin", :pass => "foobar" }).flush
  user  = http.post(auth_url, :params => { :user => "alice", :pass => "123qwe" }).flush
end
```

In the above `admin.cookies` will hold cookies with (probably some session identifier) for admin user. And `user.cookies` will hold same for user.

In other words, `Cookie::Jar` does not belong neither to connection nor client. It belong to request or response. Thus we need some wrapper that will implement request/response cookies manipulation.

**Comment by tarcieri** [comment]
@ixti what if we had a `:cookies` or `:cookie_jar` parameter on the actual request method? (e.g. `#post`)

So, in your example above:

```ruby
cookie_jar = Cookie::Jar.new

HTTP.persistent host do |http|
  # PROTIP: Don't hardcode passwords ;)
  http.post(auth_url, :params => { :user => "alice", :pass => "123qwe" }, :cookies => cookie_jar).flush

  http.get("/foo", :cookies => cookie_jar)
  http.post("/bar", :cookies => cookie_jar)
  http.headers("X-Foo" => "Bar").get("/foo", :cookies => cookie_jar)
end
```

**Comment by ixti** [comment]
@tarcieri manual handling is already working perfectly fine :D the idea behind this issue is to make it automatic. Right now one can pass cookies manually:

``` ruby
HTTP.persistent host do |http|
  # PROTIP: Don't hardcode passwords ;) and usernames too :D
  res = http.post(auth_url, :params => { :user => "alice", :pass => "123qwe" }).flush

  res = http.cookies(res.cookies).get("/foo").flush
  res = http.cookies(res.cookies).post("/bar").flush

  http.headers("X-Foo" => "Bar").cookies(res.cookies).get("/foo")
end
```

But this is not very beautiful way ;)) I will add a better variant soon.

**Comment by ixti** [comment]
Closing this in favor of #306
