### ISSUE TITLE
Close connection in case of error.

### ISSUE THREAD

**Issue by ixti** [httprb/http#269]
Right now we close connection in client upon case of error only if client is persistent. 
https://github.com/httprb/http/blob/master/lib/http/client.rb#L78

IMO that line should be just `close` without the guard.

@zanker @tarcieri thoughts?

**Comment by zanker** [comment]
I have no idea why I made it only close persistent ones. :+1: on fixing.

**Comment by sferik** [comment]
:+1:

**Comment by tarcieri** [comment]
also :+1:
