### ISSUE TITLE
Webmock broken by new HTTP::Response#initialize API

### ISSUE THREAD

**Issue by tarcieri** [httprb/http#277]
See f40fbda8: Use opts hash for HTTP::Response.new

This seems like a good change. I think we should release with this new API and update Webmock accordingly.

cc @connorhd @nerdrew @zanker

**Comment by zanker** [comment]
Sounds good. I'd like to see us do this in a way that's more backwards compatible but I'm not exactly sure if that's feasible.

**Comment by ixti** [comment]
Oh. I merged that and forgot to provide webmock adapter update. Will do that this weekend.

**Comment by ixti** [comment]
I don't see a way to make it backward compatible either. But I don't see worth in keeping API backward compatible - we just removed bunch of methods ;D we're *braking bad* already :D

**Comment by tarcieri** [comment]
Sidebar: if we do this for `Response`, should we do it for `Request` too?

https://github.com/httprb/http/blob/master/lib/http/request.rb#L67

**Comment by ixti** [comment]
Agree!

**Comment by tarcieri** [comment]
Ok, I just merged #278 which updates the `Request` API (thanks @ixti) so I guess that means we're going with a breaking API change here

**Comment by tarcieri** [comment]
I released 1.0.0.pre4 with the updated `HTTP::Request` API.

@ixti want to take a crack at fixing Webmock?

**Comment by ixti** [comment]
Yeah. Sure. Will prepare a PR for webmock today. Sure.

**Comment by ixti** [comment]
PR for webmock is: https://github.com/bblimke/webmock/pull/554
Meanwhile, I think we should move webmock integration under http gem.
So that in WebMock there will be only one line left: `require "http/webmock"`.

That will make webmock adapter always up to date with http API.

**Comment by tarcieri** [comment]
In theory this should be the last breaking change because the 1.0 API should be stable, so I'm not sure that matters?

Perhaps we should move it the next time we feel the need to change it.

**Comment by ixti** [comment]
Agree!
