### ISSUE TITLE
Drop lowercase Http support?

### ISSUE THREAD

**Issue by tarcieri** [httprb/http#280]
This library started out supporting a lowercase `Http` name, because it was cool and Ruby-ish.

Unfortunately many other gems define a toplevel `HTTP` module (including http_parser.rb, which this gem depends on), so that wasn't practical. Instead, this gem creates a constant alias to stay backwards compatible with the original API:

https://github.com/httprb/http/blob/master/lib/http.rb#L27

I think that alias can be safely dropped now. Thoughts?

**Comment by ixti** [comment]
:+1: on dropping `Http` out

**Comment by zanker** [comment]
SGs
