### ISSUE TITLE
using persistent, but keeping entire HTTP::Response object, not #to_s

### ISSUE THREAD

**Issue by jrochkind** [httprb/http#285]
Taking the [example from the docs](https://github.com/httprb/http/blob/2466ee2c5fc30cfbee3f5d2f5f7c2cbf245b0e38/lib/http/chainable.rb#L121-L123), but altering it to map entire HTTP::Response objects rather than calling #to_s on them to get message bodies...

~~~
users = %w{jrochkind tarcieri foo bar}
responses = HTTP.persistent("https://github.com") do |http|
  users.map { |u| puts "Getting #{u}/keys ..." ; http.get("/#{u}.keys") }
end
~~~

We get an exception raised on the second `get`. 

~~~
HTTP::StateError: Tried to send a request while one is pending already. Make sure you read off the body.
	from /Users/jrochkind/.gem/ruby/2.2.2/gems/http-1.0.1/lib/http/connection.rb:63:in `send_request'
	from /Users/jrochkind/.gem/ruby/2.2.2/gems/http-1.0.1/lib/http/client.rb:65:in `perform'
~~~

Is it not possible to use persistent connections and operate on HTTP::Response objects, you need to convert each response to a string body sequentially?

Is there any way to do that so it's safe, but using the full HTTP::Response API, so I have access to response headers and response code etc, not just response body, on each response?

Any advice?

**Comment by zanker** [comment]
It's not possible right now. We probably should change it so the response object isn't linked to the socket beyond the body though.

Or at least skip that check. I'll take a look in a bit.

**Comment by tarcieri** [comment]
Something needs to read off the response body between requests so the next request begins consuming the next response body at the headers.

**Comment by jrochkind** [comment]
Thanks. This limitation makes the persistent connection feature more difficult to use correctly, and less useful than it could be.

**Comment by jrochkind** [comment]
It may not be easy to implement in the actual architecture, but semantically it seems like what would be desirable is if you make a non-initial request on a persistent connection, the previous body needs to be completely read at that point.  That matches the semantics of how you actually need to use persistent HTTP connections (you can't make another request until you've finished reading the prior one), without eliminating the ability for people to read HTTP responses piece-by-piece streaming on a persistent connection if they chose to, just as they would on a non-persistent connection. But there may be no good way to make that magically happen.

**Comment by zanker** [comment]
Ah sorry I see what's happening now. Yea @tarcieri is right, you need to read the response off, so in your example

```ruby
users = %w{jrochkind tarcieri foo bar}
responses = HTTP.persistent("https://github.com") do |http|
  users.map do |u|
    puts "Getting #{u}/keys ..." 
    response = http.get("/#{u}.keys")
    response.body.to_s
    response
  end
end
```

Will work fine. We can't really automatically read off the entire thing, because we specifically support streaming as a first class feature. I agree it's not totally clear, and it might be worth revisiting by making streaming opt-in, as I expect that's not used frequently. 

That would have to be a 2.0 feature though.

**Comment by tarcieri** [comment]
Making another request could implicitly read off the old body. I think we ended up doing something like that in Reel

**Comment by zanker** [comment]
Yea we could also do that. I kind of dislike that change because it's inconsistent magic.

Then again right now it hard errors. I'm kind of conflicted and can go either way.

**Comment by jrochkind** [comment]
I think it's confusing magic to tell you that if you are making requests to
a persistent connection, you need to keep track of the order you made the
requests, and make sure to read their bodies in the right order (even if
you don't care about the body of one of them but just want the headers or
whatever). Well, not magic, whatever the opposite of magic is (voodoo
curse?)

**Comment by zanker** [comment]
Hah yea sorry, to clarify I definitely want to fix it and make it clearer. I'm not a huge fan of the mechanics changing based on persistent vs non persistent. That's why I'd rather have a flag to toggle streaming for example.

**Comment by jrochkind** [comment]
Yeah, right on. Currently, of course, the mechanics do change in persistent vs non persistent. What would be the downsides of @tarcieri's suggestion, how would it effect the API in a backwards incompat way? I am missing it.

**Comment by ixti** [comment]
to avoid `response.body.to_s` there's a syntax sugar for that in fact:

``` ruby
users = %w{jrochkind tarcieri foo bar}
responses = HTTP.persistent("https://github.com") do |http|
  users.map do |u|
    puts "Getting #{u}/keys ..." 
    http.get("/#{u}.keys").flush
  end
end
```

**Comment by tarcieri** [comment]
@ixti nice! Would be good to document that

**Comment by tarcieri** [comment]
With d278878 I think we can safely call this one closed
