### ISSUE TITLE
HTTP::URI.parse doesn’t set default port

### ISSUE THREAD

**Issue by sferik** [httprb/http#297]
The `http` gem [changed](https://github.com/httprb/http/commit/81509bc40379dcc69bad9fa9ca435552947468c6) to how it creates URIs between version 0.7 and 0.8. Versions 0.7 and earlier used the standard `URI` library, while more recent versions use a custom `HTTP::URI`, which descends from `Addressable::URI`.

After upgrading `http` dependency in the `twitter` gem from 0.6 to 0.8 (and now to 1.0), some code that expected the default port to be set is now broken. You can read a detailed write up of [the issue](https://github.com/sferik/twitter/issues/709), with the relevant portion reproduced below:

##### `http` gem 0.7.x and earlier
```ruby
[38] pry(main)> uri = URI('https://stream.twitter.com')
=> #<URI::HTTPS:0x007fa54f8d38e8 URL:https://stream.twitter.com>
[39] pry(main)> uri.port
=> 443
```
##### `http` gem 0.8.x and later
```ruby
[40] pry(main)> uri = HTTP::URI.parse('https://stream.twitter.com').normalize
=> #<Addressable::URI:0x3fd2a57bd650 URI:https://stream.twitter.com/>
[41] pry(main)> uri.port
=> nil
```

@tarcieri @zanker @ixti **How would you feel about adding back the default ports (80 for HTTP and 443 for HTTPS) if an explicit port is not specified?**

Quoting from [RFC 7230, section 2.7.1](https://tools.ietf.org/html/rfc7230#section-2.7.1) on http URI Scheme:

> If the port subcomponent is empty or not given, TCP port 80 (the reserved port for WWW services) is the default.

And [the subsequent section](https://tools.ietf.org/html/rfc7230#section-2.7.2) on the https URI Scheme:

>  All of the requirements listed above for the "http" scheme are also requirements for the "https" scheme, except that TCP port 443 is the default if the port subcomponent is empty or not given…

If we all agree this is the correct behavior, I will work on a patch.

**Comment by tarcieri** [comment]
Definitely sounds like the correct behavior to me, and a bug in Addressable...

**Comment by sferik** [comment]
@tarcieri I just looked at the Addressable code and realized they solve this by providing [`default_port` and `inferred_port`](https://github.com/sporkmonger/addressable/blob/295d7baec1281976434e9061b8065979b3f38c83/lib/addressable/uri.rb#L1351-L1373) methods. Perhaps that’s fine for HTTP? But it was surprising to me that the `port` method would return `nil` when a port is not set explicitly, especially since that was not the behavior of earlier versions of this library. To me, it would make more sense to have an `explicit_port` method that would be `nil` if the port is not set explicitly.

**Comment by zanker** [comment]
I'd agree with @tarcieri. It's annoying that it broke between the two, but returning a nil makes sense to me. Having an explicit method is :+1:

**Comment by tarcieri** [comment]
@sferik hmm, I think it's a bit strange that `HTTP::URI` diverges from `URI` like that. There was also some recent discussion about removing Addressable due to performance reasons.

**Comment by ixti** [comment]
@sferik We can do that in our inherited URI class

**Comment by ixti** [comment]
@tarcieri re removing Addressable. Before doing that we should first do our own research.
Because Addressable does pretty awesome job in:

- IDNA support `Addressable::URI.parse "http://привет-мир.рф"`
- UTF support `https://en.wikipedia.org/wiki/A_Coruña` (see: https://github.com/httprb/http/pull/197)
- nice utilities like `#join`

Yes, `Addressable::URI.parse` slower than `URI.parse`.
Yes `Addressable` takes pretty much RAM `1.6MB`...

But I don't see how something that simply does not fit our need but lightweight might be better ;))

**Comment by tarcieri** [comment]
@ixti sure, I don't think there's even an open issue about removing Addressable, just some discussion. I was just throwing it out there as something that has come up in the past.

**Comment by ixti** [comment]
@tarcieri Yeah. I guess I wrote that up mostly for myself ;)) as in that discussion I was on the side of removing it :D

**Comment by ixti** [comment]
For reference. Discussion me and @tarcieri were talking about is: https://github.com/httprb/http/pull/197#issuecomment-170556459

**Comment by tarcieri** [comment]
@sferik do you still consider this an open problem? Should we perhaps open a new one about getting rid of `Addressable`?

@ixti getting rid of `Addressable` is something we should consider before a 2.x release...

**Comment by tarcieri** [comment]
I made an issue for a 2.0.0 release: #321

**Comment by sferik** [comment]
@tarcieri Thanks. Other than this, I don’t have any 2.0 blockers.

**Comment by ixti** [comment]
I don't think we should get rid of Addressable completely. Maximum what I think we should do (if we want to get rid of hard addressable dependency) is to provide our own class for URI, that will use internally stdlib URI by default and will be able to handle URIs with addressable: `HTTP::URI.use :addressable`.

**Comment by tarcieri** [comment]
Yeah, let's get rid of `HTTP::URI < Addressable::URI` at least. It should use object composition instead of a subclass.
