### ISSUE TITLE
Normalized Response Headers

### ISSUE THREAD

**Issue by aaronchi** [httprb/http#300]
It seems that header names are normalized when they are added to the response body, so in some cases, the values reported by http are not the actual values returned by the server. Is there any way to access the original header names in the response before they are normalized or remove normalization for response headers?

**Comment by tarcieri** [comment]
The best we could offer is a flag to disable this behavior. Any particular reason why you want the original headers? They should only differ by case...

**Comment by aaronchi** [comment]
I'm moving over from a different driver and noticed that certain headers I was looking for don't get located  correctly because of the normalization.

It seems like normalization is a convenience method for setting headers in the request, but shouldn't necessarily be applied to the response since these are the actual values being sent from the server.

**Comment by tarcieri** [comment]
Header normalization applied to the server response is useful when looking for standard headers which may be served in varying cases, which is needed for the internal operation of the library.

Again, a flag to shut it off might be doable...

**Comment by ixti** [comment]
Generally it's doable to provide a way to get original name and normalized one. But I also don't see any value in this, so probably a flag to disable headers normalization is better idea.

**Comment by aaronchi** [comment]
I think I will just treat response headers as case insensitive in my code. Thanks.

**Comment by ixti** [comment]
:D
