### ISSUE TITLE
IOError / EOFError not subclassed from HTTP::Error

### ISSUE THREAD

**Issue by julik** [httprb/http#303]
I am using http.rb in a threaded application for doing downloads, and my error handling code is somewhat more involved because I have a set of exceptions I consider retriable. Ideally I would insert all the descendants of `HTTP::Error`, or `HTTP::Error` itself into my array of retriables, but the actual sync read methods can also raise IOError and EOFError. Would it not be wiser to have subclass versions of these from HTTP::Error and let the caller check the `Exception#reason` if desired to get at the real IO error object?

**Comment by zanker** [comment]
I think it's a good idea, but we'd need to do it as part of 2.0 I think. @tarcieri @ixti @sferik thoughts?

**Comment by ixti** [comment]
:+1: on this!

**Comment by tarcieri** [comment]
:+1: on this, but like @zanker it's a breaking API change. Fortunately we're planning on shipping 2.0 soon to drop Ruby 1.9 support.

**Comment by julik** [comment]
@tarcieri thanks!
