### ISSUE TITLE
Got SSL related error

### ISSUE THREAD

**Issue by hbzhang** [httprb/http#304]
I tried to use this GEM. However I got the error:

OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

The site I am trying to access is a SSL site. Please help. Thanks!

**Comment by tarcieri** [comment]
Can you post a link to the server in question?

This error indicates an SSL/TLS protocol mismatch between client and server. You either have an out-of-date version of OpenSSL installed locally, or the server has an out-of-date SSL configuration.

**Comment by hbzhang** [comment]
Can I just pass by the SSL option. I think Ruby built in http has the option to ignore the SSL connection. My server is OpenSSL 1.0.1e-fips 11 Feb 2013.

I am not sure the SSL configuration of the server I am connecting to.

Thank you!

**Comment by tarcieri** [comment]
We do not provide a first-class API for using HTTPS insecurely by-design.
However, we do let you pass in a custom SSLContext object you can configure
to be as secure or as insecure as you desire. The API is documented here:

https://github.com/httprb/http/wiki/HTTPS


-- 
Tony Arcieri

**Comment by hbzhang** [comment]
Thank you for the help. I just made a simple trick, instead of GET or POST to the HTTPS based URL, i did it with HTTP based URL. It seems the gem does not complain the SSL error anymore.

**Comment by scrozier** [comment]
FWIW, this works for me to ignore server certificate errors:

    ctx = OpenSSL::SSL::SSLContext.new
    ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE

Then pass `ssl_context: ctx` as your final parameter to HTTP.post
