### ISSUE TITLE
Ignore SSL certificate errors, like curl -k?

### ISSUE THREAD

**Issue by scrozier** [httprb/http#308]
I need this...is there an existing way to get this behavior already?

**Comment by tarcieri** [comment]
See #304

>

-- 
Tony Arcieri

**Comment by scrozier** [comment]
Thanks, tarcieri. After some trial and error, the following worked for me:

    ctx = OpenSSL::SSL::SSLContext.new
    ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE

Then pass `ssl_context: ctx` as your final parameter to HTTP.post.

**Comment by xanview** [comment]
This works but feels like a messy workaround and is a pain to have to repeat in every single request. Can maybe something like this be added? <

```ruby
HttpClient..insecure.get('https://192.168.0.100:4433/system/partitions/')
```

To mimic the --insecure option of curl?

**Comment by ixti** [comment]
I think `#insecure` is a good idea in general.
