### ISSUE TITLE
Working with the raw socket after header are all read and parsed

### ISSUE THREAD

**Issue by julik** [httprb/http#310]
I need to write a _very_ high volume HTTP downloader which performs multiple requests in succession and writes responses to files. In my experiments with my toy HTTP client I have determined that to have the least GC pressure I need to reuse a String as an `outbuf` as per Ruby documentation.

```
socket.read_nonblock(chunk_size, body_buf)
```

In contrast with the `readpartial` there is no String allocation per call, which seems to be detrimental to keeping memory usage low. With the toy client and downloads of about 5MB I can consistently keep it at 18 MB RES on OSX (MRI 2.2.2). Apparently I can _flatten_ my memory use throughout a large number of downloads that all have to happen within the same process. 

So I know it is a tall order (dunno what the appropriate tag is - "pondering" maybe?), with the HTTP parser being in the picture, but  was wondering if I could get at the socket to do this once the parser has finished with the headers/status? So far it seems I would need to go to the `Response`, then to `Client`, then to `Connection` (and `Connection` doesn't even expose the socket)... but maybe I am missing something?

Or maybe there is a different way to do download-to-file for multiple large bodies without too much object space saturation?

**Comment by tarcieri** [comment]
Have you considered using a client which can do this natively in C? If your goal is to get an HTTP response into a file, round-tripping it through a Ruby VM is probably not the most efficient option.

**Comment by julik** [comment]
I did, so far only found Patron that supports it using the curl option for CURLOPT_WRITEDATA. Maybe adding a direct-to-FD feature would make sense for HTTP.rb too?

**Comment by tarcieri** [comment]
Converting everything to a direct buffering model is a PR we might accept but unless you want to work on it yourself it probably isn't going to happen.

**Comment by julik** [comment]
Fair enough. Will close for now.
