### ISSUE TITLE
Stack trace when requiring the HTTP gem from Faraday

### ISSUE THREAD

**Issue by bbozo** [httprb/http#311]
Hello all :)

I gave it a go to write the `HTTP` plugin for Faraday with `Celluloid::IO` support https://github.com/lostisland/faraday/pull/564 - and on C Rubies 1.9.3+ and JRuby in mode 20+ I get this stack trace in the test: https://gist.github.com/bbozo/6f97a19f34d8b8961db8

I'm not sure if it's something to be concerned about, also it possibly breaks the CI tests, so I'm wondering if it's something i need to fix, or if it is something I can safely work around in some manner?

**Comment by bbozo** [comment]
Sorry, my idiot ^_^

**Comment by bbozo** [comment]
The people from Faraday says that the stack trace in the tests breaks the CI build, so I went to investigate what triggers it.

I put a `binding.pry` breakpoint before [this](https://github.com/bbozo/faraday/blob/httprb_support/lib/faraday/adapter/http_gem.rb#L4) and [this](https://github.com/bbozo/faraday/blob/httprb_support/lib/faraday/adapter/http_gem_celluloid_io.rb#L8) line, and then I did a `require 'http'` manually and got this:

https://gist.github.com/bbozo/a1411649c0bfacf29890eccf39be1f5f

Do you have an idea why this could be happening and if it is a source of concern for the Faraday integration?

**Comment by tarcieri** [comment]
None of that looks related to http.rb.

Also note that we dropped Celluloid::IO support some time ago when we added the new timeout backend.

**Comment by bbozo** [comment]
Thank you @tarcieri

**Comment by bbozo** [comment]
PS do you suggest that I drop `Celluloid::IO` integration from the Faraday adapters? Is there an alternative HTTP lib working with Celluloid::IO (maybe I mixed something up, but iirc other libs used to block) ?

**Comment by tarcieri** [comment]
@bbozo I'd like to bring Celluloid::IO support back at some point, but it would require doing a lot of work on the timeout backend which I don't have time to do.
