### ISSUE TITLE
Support common mime types

### ISSUE THREAD

**Issue by kylekyle** [httprb/http#313]
It would be nice to support the parsing the of the `text/html` and `application/xml` MIME types. `text/html` should just return the response contents as a `String`, and `application/xml` could be returned as a `Nokogiri::XML` document.

**Comment by tarcieri** [comment]
How is it helpful to have a `#parse` that's a no-op?

re: nokogiri, I think it's ok so long as it's *optional*. I do not think it makes sense to make nokogiri a hard dependency of this library

**Comment by kylekyle** [comment]
Yeah, the `text/plain` adapter is a no-op, but without it users have to remember to call `.body.to_s` instead of `#parse`, which is a little annoying. It is nice to use `#parse` for consistency.

You're right about the `nokogiri` dependency. It's a big one. I removed the dependency from the spec and changed the adapter to check if `nokogiri` is available when `#parse` is called. If it's not available, it recommends the user install it. If you want to test it, install your bundle with the `--without development` option.

**Comment by tarcieri** [comment]
> users have to remember to call .body.to_s instead of #parse

You can just call `#to_s` on a response object. No need to call `#body` first.

**Comment by kylekyle** [comment]
Ah! I didn't know that. Thanks! Unless you object, it would still be nice to support the `text/plain` MIME type for consistency.

**Comment by tarcieri** [comment]
I think I'm with @ixti's response on #315. If you'd like this, it's specifically designed to be pluggable so you can include your own plugins and release them in your own gem if you want. Otherwise I don't think it makes sense out-of-the-box.
