### ISSUE TITLE
Prevent header renaming?

### ISSUE THREAD

**Issue by mhenrixon** [httprb/http#317]
How can I prevent header renaming? I need to provide headers with an underscore and I can't find a way to achieve this.

**Comment by ixti** [comment]
Can you explain why you might need this?

**Comment by ixti** [comment]
You're not the first one who was asking this question, so I'm pretty concerned if this is really needed feature (we can probably allow pass header names without normalization)

**Comment by mhenrixon** [comment]
For me it turned out it wasn't needed I just thought it was when I got different errors from CURL when I changed the name of the headers.

**Comment by ixti** [comment]
Ah. OK. Thanks.

**Comment by tarcieri** [comment]
I think in general the way we process headers could use some work (and was a regression from my previous code). We *always* do duplicate allocations for headers, even if they already match the canonical format.

I think we should check first if they match the canonical format, in which case the duplicate allocations should be skipped. Right now we always check and always allocate.

**Comment by ixti** [comment]
> was a regression from my previous code

Fixed in: #318
