### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by tarcieri** [httprb/http#321]
We're about to do a major version bump to drop Ruby 1.9 support (see #242). This is a last call for any additional breaking API changes before that happens.

The only one I think we might consider making is #297 (tl;dr: drop support for `Addressable` due to performance concerns, see also https://github.com/httprb/http/pull/197#issuecomment-170556459)

Any others, or :shipit:?

**Comment by tarcieri** [comment]
Perhaps we should do #303 as well

**Comment by tarcieri** [comment]
#323 seems relevant as well

**Comment by tarcieri** [comment]
See also comments on #206. I think we should ditch Addressable.

**Comment by tarcieri** [comment]
Ok, well with #325 in place (which closes #297), I think we have a path forward for Addressable. I'd suggest we do #303 and call it good.

**Comment by tarcieri** [comment]
I just released `2.0.0.pre` after doing a number of fixes (#297 and #303 are fixed among others)

If anyone would like to try it out, that'd be great. That said, I think I'm otherwise happy with the current state of `master`

**Comment by tarcieri** [comment]
Unless anyone has any objections, I'd like to ship the current master as 2.0.0 this Saturday (April 23rd)

**Comment by zanker** [comment]
Seems fine

**Comment by sferik** [comment]
🚀

**Comment by tarcieri** [comment]
2.0.0 is released! I'll make an announcement shortly
