### ISSUE TITLE
URL with underscores don't work

### ISSUE THREAD

**Issue by 907th** [httprb/http#323]
HTTP incorrectly converts `sms_service.mysite.com` URL into `sms%5Fservice.mysite.com`. And then my request fails with `HTTP::ConnectionError: failed to connect: getaddrinfo: Name or service not known` error.
PS. curl for the same URL works fine.

**Comment by 907th** [comment]
My teammate thinks that this issue should be fixed in the Addressable gem. So he created a [similar issue] (https://github.com/sporkmonger/addressable/issues/233) in that gem.

**Comment by tarcieri** [comment]
Addressable has been the source of a lot of problems, I think. We've discussed removing it (or at least minimizing its usage) in a 2.0 release.

**Comment by tarcieri** [comment]
One thing I should note on this: underscores aren't technically allowed in domain names (only `[a-z0-9\-]`)

**Comment by 907th** [comment]
@tarcieri You're right, they are [not allowed](http://tools.ietf.org/html/rfc1034#section-3.5) in DNS names. Thanks!

**Comment by tarcieri** [comment]
I suggest either fixing your URLs or fixing Addressable.

**Comment by sporkmonger** [comment]
@tarcieri I'd actually be really interested in hearing more about where Addressable has been a problem.

**Comment by tarcieri** [comment]
@sporkmonger #297 has most of the discussion. For what it's worth I don't think we're planning on removing it anymore.
