### ISSUE TITLE
Set JSON enocoding

### ISSUE THREAD

**Issue by kylekyle** [httprb/http#324]
The 'Content-Type' header for JSON should include the encoding of the JSON the gem generates. It's usually UTF_8, so it would be: `Content-type: application/json; charset=utf-8`

**Comment by ixti** [comment]
Will `#encoding` of a string will be enough?

**Comment by ixti** [comment]
So I guess changing [this](https://github.com/httprb/http/blob/master/lib/http/client.rb#L164):

``` ruby
headers[Headers::CONTENT_TYPE] ||= "application/json"
MimeType[:json].encode opts.json
```

to:

``` ruby
body = MimeType[:json].encode opts.json
headers[Headers::CONTENT_TYPE] ||= "application/json; #{body.encoding.name}"
body
```

should be OK. Right?

**Comment by kylekyle** [comment]
You're missing the `charset=` bit.

**Comment by ixti** [comment]
Oh, yeah. Sorry. I mean `... charset=#{body.encoding.name}"` of course. Thanks!
