### ISSUE TITLE
Headers with leading underscore being rewritten to dashes

### ISSUE THREAD

**Issue by peterc** [httprb/http#337]
Similar to #317 

I'm coding against a (popular) API that claims to support DELETE but which, sadly, does not. It requires you POST and set a _method header to POST instead.

Unfortunately, setting a "_method" header results in HTTP::Headers.normalize_header changing the "_" to a "-" as part of its normalization process and the header becomes "-Method" which doesn't work.

I believe the first line of normalize_header is in error to only return the existing header name if it is already in canonical form. I believe it should return if it is already _compliant_ instead. Doing this resolves the issue in my case. That is, a simple change from:

```
return name if name =~ CANONICAL_NAME_RE
```

to 

```
return name if name =~ COMPLIANT_NAME_RE
```

Could someone with more knowledge than me verify if my assertions above are correct? If so, I am more than happy to put in a pull request, and even more happy if someone just wants to make the change (or explain why this behavior is desirable, naturally) :-)

**Comment by tarcieri** [comment]
@peterc at least for responses, we try to canonicalize the headers so things building abstractions on top of this library can rely on the canonical name.

The same does not hold true of requests, however.

**Comment by peterc** [comment]
Good point, that makes sense for response headers.

I am not sure what this means for legitimate (if ugly) request headers, though. In the interim, however, for anyone who runs into the same issue, I am using the following patch to silently protect leading-underscore headers:

`module HTTP
	class Headers
		alias old_normalize_header normalize_header

		def normalize_header(name)
			return name if name.start_with?('_')
			old_normalize_header(name)
		end
	end
end`

**Comment by ixti** [comment]
I would ask why non-standard field is not prefixed with `X-` as proposed in RFC, but I believe nobody knows ;)) Anyway, one of the main reasons behind "normalization" of headers is, as @tarcieri already pointed out making sure they are easily accessible from whatever stuff on top of http gem.

I agree that we probably should not normalize headers for requests. Alternatively, we can provide a blacklist of normalization instead.

**Comment by ixti** [comment]
I mean configurable blacklist of course.

**Comment by peterc** [comment]
Yeah, `X-Http-Method-Override` is a common (and far easier to deal with) alternative/synonym for `_method` but appears not to work with the API in question, alas :-( (The API is a financial one almost exclusively used from Java and .NET code, which might explain why I'm mostly discovering these things in the dark 😂)

**Comment by ixti** [comment]
I'm totally fine with allowing request to have non-normalized headers, but that will most likley need api change. E.g. I know that lots of people do `HTTP.headers(:content_encoding => "...")`, or at least I do that :laughing:

Probably we can provide an extra api like:

``` ruby
HTTP.raw_headers("_method" => "DELETE")
```

that will serve this purpose, but I think it might worth adding a globally known ugly header names that should not be normalized. Or should be denormalized instead:

``` ruby
HTTP::Headers::DENORMALIZED = { "-Method" => "_METHOD" }
```

**Comment by ixti** [comment]
Both variants seems good to me, although I lean toward first one ;))

**Comment by ixti** [comment]
On the other hand, second variant is easier to achieve. :D

**Comment by ixti** [comment]
@httprb/core RFC

**Comment by tarcieri** [comment]
I would rather have a generic API than whitelisting people's errata.

@peterc this API really demands a `_method` *header* instead of just a param? Seems kinda wacky to me.

**Comment by tarcieri** [comment]
Looking at `normalize_header`, I'm curious why it converts `_` to `-`

**Comment by ixti** [comment]
@tarcieri To make it normalized :-P

```
content_length => Content-Length
x_what_ever => X-What-Ever
```

We can actually re-work headers class to store both normalized and non-normalized header names and a flag whenever that header should be sent raw or normalized. I like idea of extra API better as well.

**Comment by peterc** [comment]
@tarcieri I'll see if it works with a param, but after a cpl hours pulling my hair out the other night, I noticed in their own "API explorer", it was setting that header and using POST. When I replicated this using your library, it also failed, until I printed out exactly what was going out over the wire, then wrote my workaround. So yeah, not the world's best API ;-) Separate to that, though, it is a legitimate HTTP header, if a horribly designed and uncommon one, so I felt it was legitimate to raise here at least :-)

I have another idea to throw into the mix.

I totally understand why you'd want symbols normalizing back and forth, but what if a string were explicitly supplied? In that case, I'd expect it to remain verbatim. Could Symbol vs String determine whether normalization occurs, perhaps?

**Comment by zanker** [comment]
Having an API that adds something like `raw_headers` makes sense for me, since we can't really predicate what people come up with (like this `_method` one). I'd like to stay away from type based APIs though personally, just because that can get confusing.

**Comment by ixti** [comment]
I also think that type based APIs might cause confusion.

**Comment by tarcieri** [comment]
@ixti ugh @ normalizing snake case symbols. I buy the rest of the normalization behavior (in fact I think I originally implemented it) but that seems a tad odd to me

**Comment by ixti** [comment]
> in fact I think I originally implemented it

 yup! :smile: 

> mangling symbols this way and not strings I think. I guess you don't though

yup! :laughing: 

I'm a bit overdosed with magic in some other gems already :wink:

**Comment by britishtea** [comment]
Reading through [`spec/lib/headers_spec.rb`](https://github.com/httprb/http/blob/master/spec/lib/http_spec.rb) almost all methods defined on `HTTP::Headers` perform normalization. Adding a `#raw_headers` option will not be sufficient: raw header names such as `"_method"` cannot be looked up or deleted.

To mitigate this there are two solutions:

1. Giving each header a tag indicating wether it was set as raw or not. This adds quite a bit of complexity I imagine.
2. Implement `#set_raw`, `#get_raw`, `#include_raw?`, etc. This is not a very pleasant API to work with.

A third solution (with caveats) would be to make the current methods "smarter" by first checking for presence on the raw header name. This may be problematic in the (hypothetical) case were you have both a `"_method"` and `"-method"` header.

**Comment by tarcieri** [comment]
I would still suggest adding `#raw_headers`...

What I think might make a lot of sense here is to store a raw headers hash, and handle normalization through a proxy object which would more or less preserve the current API but normalize headers at the time they're accessed. This would make the normalization transforms side-effect free, as opposed to the current mangling solution.

 I don't understand the "Adding a #raw_headers option will not be sufficient" comment above. Would using a proxy object mitigate it?

**Comment by britishtea** [comment]
@tarcieri Perhaps I should phrase it as "**only** adding a `#raw_headers` option will not be sufficient; `HTTP::Headers` will need changing too :)

The solution you propose will work, I believe, with the caveat that `HTTP::Headers` won't be able to tell the difference between `_method` and `-method` when accessing. This is probably not an issue in practice.

**Comment by r-obert** [comment]
all this trouble so you don't have to write `'Content-Type' =>` instead of `content_type:` ? :smile: dual APIs (headers and raw_headers) sounds confusing, and it would exist because of normalisation logic that is buggy and always will be, the solution proposed is to avoid the bug by adding a new API. 

i liked string vs symbol being used to opt-in or out, because it's subtle and i never use symbols for header names (i write them as they should be, so 'Content-Type' etc). i also feel normalisation stuff like this hides what is really sent to the server, and doesn't help people trying to learn http.

2c. :wink:

**Comment by mikegee** [comment]
I think the next step would be for someone to open a PR based on this discussion. There seems to be sufficient clarity from @tarcieri on what would be acceptable.

**Comment by ixti** [comment]
I will try to find some time to work on that. If somebody willing to start that earlier - feel free to poke me - will be happy to assist

**Comment by ace** [comment]
Hi. I know this is not the intended solution, but I needed something quick and tried the 'don't normalize Strings' option (kind of). If the header name is a String and is already compliant, I use it as it is, otherwise, I go on with the normalization.

This is the monkey patch file in my Rails project, in case it may be useful to someone else. It just removes the `.to_s` in all the calls to the `normalize_header` method and adds the two first lines in that method.

```
module HTTP
  # HTTP Headers container.
  class Headers
    # Removes header.
    #
    # @param [#to_s] name header name
    # @return [void]
    def delete(name)
      name = normalize_header name
      @pile.delete_if { |k, _| k == name }
    end

    # Appends header.
    #
    # @param [#to_s] name header name
    # @param [Array<#to_s>, #to_s] value header value(s) to be appended
    # @return [void]
    def add(name, value)
      name = normalize_header name
      Array(value).each { |v| @pile << [name, v.to_s] }
    end

    # Returns list of header values if any.
    #
    # @return [Array<String>]
    def get(name)
      name = normalize_header name
      @pile.select { |k, _| k == name }.map { |_, v| v }
    end

    # Tells whenever header with given `name` is set or not.
    #
    # @return [Boolean]
    def include?(name)
      name = normalize_header name
      @pile.any? { |k, _| k == name }
    end

    private

    # Transforms `name` to canonical HTTP header capitalization.
    # PATCH: If it is a String and matches COMPLIANT_NAME_RE, then return it as is.
    #
    # @param [String] name
    # @raise [HeaderError] if normalized name does not
    #   match {HEADER_NAME_RE}
    # @return [String] canonical HTTP header name
    def normalize_header(name)
      return name if name.is_a?(String) && name =~ COMPLIANT_NAME_RE

      name = name.to_s
      return name if name =~ CANONICAL_NAME_RE

      normalized = name.split(/[\-_]/).each(&:capitalize!).join("-")

      return normalized if normalized =~ COMPLIANT_NAME_RE

      raise HeaderError, "Invalid HTTP header field name: #{name.inspect}"
    end
  end
end
```

**Comment by mofahead** [comment]
Just wanted to comment that I got bit by this too. I'm working with an API which requires a custom request header that looks like this: "X-LongNameInCamelCase". Unfortunately the header name seems to be case-sensitive. As far as I know http field names shouldn't be case-insensitive; nonetheless, it means that I can't use http.rb for this project without patching.

**Comment by ixti** [comment]
I'm gonna work on this shortly.

**Comment by elit69** [comment]
thank @ace 
I was considering use other library

**Comment by shaicoleman** [comment]
The following monkey-patch will prevent normalizing any header that contains an underscore
```
# Monkeypatch workaround for underscores in headers: https://github.com/httprb/http/issues/337
raise 'This Monkeypatch is only tested for http 4.2.x' unless Gem.loaded_specs['http'].version.to_s.starts_with?('4.2.')

module DontNormalizeUnderscoreHeaders
  def normalize_header(name)
    return name if name.include?('_')

    super
  end
end

module HTTP
  class Headers
    prepend DontNormalizeUnderscoreHeaders
  end
end
```

**Comment by joshuaflanagan** [comment]
This issue was fixed by https://github.com/httprb/http/pull/576 and can be closed.

**Comment by ixti** [comment]
Indeed. Thanks @joshuaflanagan
