### ISSUE TITLE
Processing incoming data from a server?

### ISSUE THREAD

**Issue by hdt80** [httprb/http#347]
I've looked at the docs, and I'm unable to find a way to print out the data coming in from a `persistent` connection. 

I'm connecting to a server using `HTTP.persistent`, and I can use `.get` to get responses, but I would I constantly read in from a connection - from say keep-alive requests?

**Comment by tarcieri** [comment]
Use `#readpartial` if you'd like to stream data. It's documented in the README here:

https://github.com/httprb/http#basic-usage

Also, please ask questions like this on the mailing list in the future. The issue tracker is for bugs / new features.
