### ISSUE TITLE
Not verifying SSL

### ISSUE THREAD

**Issue by Fred-JulieDesk** [httprb/http#354]
Hi,

I recently tried to ignore SSL verification when calling an endpoint of mine over HTTPS. I'm developping and using a self signed certificate.

I switched to your gem because previously using http-client, I found a memory hole in timeout.rb used by this gem.

Http-client allow to bypass ssl verification by doing something like 

``` ruby
client = HTTPClient.new(default_header: {
                "Authorization" => '123'
              })
client.ssl_config.verify_mode = 0
```

I tried something similar with your gem :

``` ruby
client = HTTP.auth(url)
ctx     = OpenSSL::SSL::SSLContext.new
ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE

client.get(params[:url], ssl_context: ctx)
```

However, the certificate is still being verified when calling the endpoint and i get the following error: 'hostname "xxx" does not match the server certificate'. Which seems normal because I didn't specified a certificate.

So, is it possible to bypass the ssl verification when using your gem (as with http-client) if yes how couldi achieve it?

Many thanks,

**Comment by tarcieri** [comment]
We don't provide a first-class API for this. See #308 for a similar inquiry.
