### ISSUE TITLE
windows 'get using  basic_auth always returns 401 (unauthorised)

### ISSUE THREAD

**Issue by thebenjy** [httprb/http#374]
Code works on mac os x
Using same code on windows 7 always returns 401. Note had to fix cert issue setting SSL_CERT_FILE.  (versions below).

**code**
```
	response=HTTP.headers(:accept => "application/json").basic_auth(:user => username,:pass => password).get(url)
  return response
# always returns 401 on win 7
```

anything I've missed?

Ben

versions
`ruby 2.0.0p647 (2015-08-18) [i386-mingw32]`

gems
```
http (2.0.3)
http-cookie (1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
```

`set SSL_CERT_FILE=C:\Bitnami\rubystack-2.0.0-34\ruby\lib\ruby\site_ruby\2.0.0\rubygems\ssl_certs\cacert.pem`

**Comment by ixti** [comment]
Can you try that with Ruby `2.2.x+`? Most likely the issue has nothing to do with http gem directly, but with something in ruby itself.

**Comment by thebenjy** [comment]
thanks ixti - i probably should have tried before (was hoping not to as its a legacy ruby shoes app)

I have tried now it fully breaks the SSL access issue (SSL_CERT_FILE override not working), and will have to keep trying to fix this before I get to the auth bit...

**Comment by tarcieri** [comment]
I am guessing this isn't actually an http.rb bug. Please reopen if otherwise.
