### ISSUE TITLE
#readpartial is not respecting max length argument

### ISSUE THREAD

**Issue by akelmanson** [httprb/http#384]
Hi there,

According to [`IO#readpartial`](https://ruby-doc.org/core-2.2.2/IO.html#method-i-readpartial) documentation, this method "reads at most maxlen bytes from the I/O stream", but `HTTP::Response::Body#readpartial` is returning more bytes than expected.

    HTTP.get('http://www.rubydoc.info/github/httprb/http').body.readpartial(10).length

[oj](https://github.com/ohler55/oj) calls this method within C code and this misbehavior leads to Segmentation fault.

Thank you!

**Comment by ixti** [comment]
Can you please provide a simple example that will reproduce the issue? Because `Body` delegates `#readpartial` to `IO` at the end in fact with given `maxlen`.

**Comment by ixti** [comment]
I confirm issue exists:

``` ruby
response = HTTP.get('http://www.rubydoc.info/github/httprb/http')
5.times { puts response.body.readpartial(10).length }
# 5401
# 10
# 10
# 10
# 10
```

**Comment by ixti** [comment]
The issue is because we read response headers first. And once they are fully fetched some of body might happen to be written in the chunk waiting for the first `readpartial` call.

**Comment by bidiu** [comment]
Sorry, this is irrelevent to this issue, but have some correlation: how to detect the end of the stream?
I am new to httprb, and I am using persistent connection. I assume because the connection isn't close, there is no eof after read out all the response body bytes. Right now I am stuck in loop. Could you give me some clue? The documentation not that informative.

**Comment by tarcieri** [comment]
@bidiu please ask on the Google Group:

https://groups.google.com/forum/#!forum/httprb

**Comment by bidiu** [comment]
@tarcieri Okay, and sorry, I will delete my replies soon.

**Comment by tarcieri** [comment]
@bidiu no worries, just FYI that's the proper place to ask

**Comment by bidiu** [comment]
@tarcieri Thanks!

**Comment by bidiu** [comment]
@tarcieri No need to ask now, just checked the source of Response#each, figured it out: D
