### ISSUE TITLE
Unknown MIME type: application/hal+json

### ISSUE THREAD

**Issue by ezilocchi** [httprb/http#403]
I'm getting this error when the response from the server is coming with `Content-Type:application/hal+json; charset=utf-8`. Is any other type different from `json` supported by this gem? If not is there any plan to support this kind of new mime types?

**Comment by tarcieri** [comment]
Are you calling `HTTP::Response#parse`? Can you post a backtrace?

This error normally shouldn't arise simply because the server sent you a response with an unknown MIME type.

**Comment by ezilocchi** [comment]
So, this is the backtrace
```
HTTP::Error: Unknown MIME type: application/hal+json
/.../ruby/gems/2.3.0/gems/http-2.2.1/lib/http/mime_type.rb:37:in `[]'
```
and it makes sense based on the content of that [line](https://github.com/httprb/http/blob/5bbaecc628fbd045446aeaac465f8eade91d6851/lib/http/mime_type.rb#L37)
```ruby
adapters[normalize type] || raise(Error, "Unknown MIME type: #{type}")
```
The only adapter registered by default is [lib/http/mime_type/json.rb](https://github.com/httprb/http/blob/master/lib/http/mime_type.rb)

Since the only thing  I need is to parse response content as a standard JSON, but with `Content-Type:application/hal+json`, I can probably do something like this when I initialize the gem:
```ruby
HTTP::MimeType.register_adapter 'application/hal+json', HTTP::MimeType::JSON
```
What do you think?

PS: Thanks for the quick answer 😊

**Comment by tarcieri** [comment]
Well, you're missing the rest of the backtrace, but I think you answered my question: you're using `#parse`

Yes, `#parse` only works on registered MIME types. And yes, registering a MIME type for what you want to parse should fix the problem.

**Comment by ixti** [comment]
Yes. `#parse` works with registered mime types only unless specific adapter is explicitly requested. So you should either register adapter the way you did or pass `:json` to `#parse`:

``` ruby
HTTP.get(url).parse(:json)
```

**Comment by ezilocchi** [comment]
Nice, thanks for the Advice. I tried the first approach (register the adapte) and it worked but I like this other way, looks easier :). Thanks!

I'm closing this issue since this is the answer:

OPTION 1: register an adapter: 
```ruby
HTTP::MimeType.register_adapter 'application/hal+json', HTTP::MimeType::JSON
```

OPTION 2: pass `:json` params to the parse method
```ruby
HTTP.get(url).parse(:json)
```

**Comment by ixti** [comment]
Just for sake of giving more examples. In one project I have:

``` ruby
module HTTP
  module MimeType
    # HTML decode MIME type adapter
    class HTML < Adapter
      # Decodes HTML
      def decode(str)
        ::Nokogiri::HTML str
      end
    end

    register_adapter "text/html", HTML
    register_alias   "text/html", :html
end
```

**Comment by bknarendra** [comment]
@ixti A correction in your above example. An "end" is missing for module.
module HTTP
  module MimeType
    # HTML decode MIME type adapter
    class HTML < Adapter
      # Decodes HTML
      def decode(str)
        ::Nokogiri::HTML str
      end
    end

    register_adapter "text/html", HTML
    register_alias   "text/html", :html
  end
end

**Comment by ixti** [comment]
@bknarendra Oh. indeed! Thanks!
