### ISSUE TITLE
Documentation for following redirects

### ISSUE THREAD

**Issue by janko-m** [httprb/http#411]
I noticed that following redirects isn't mentioned in the wiki documentation, so I'm submitting this as a pull request to the wiki.

--------

# Redirects

## Automatically following redirects

The `HTTP.follow` option can be used for automatically following redirects:

```rb
response = HTTP.follow
               .get("https://example.com")
```

## Limiting number of redirects

A maximum of 5 subsequent redirects will be allowed by default (anything more
will raise a `HTTP::Redirector::TooManyRedirectsError`), but you can change the
limit with the `:max_hops` option:

```rb
response = HTTP.follow(max_hops: 3)
               .get("https://example.com")
```

## Unsafe redirects

If a POST, PUT or DELETE request returns a 300, 301 or 302 redirect response,
it won't be followed by default and `HTTP::StateError` will be raised. You can
set `:strict` to `false` if you want these redirects to be followed, in which
case the GET verb will be used for that redirect.

```rb
response = HTTP.follow(strict: false)
               .get("https://example.com")
```

**Comment by ixti** [comment]
I have unlocked WIKI from editing. Please, add your changes there! And thanks once again!

**Comment by janko-m** [comment]
Thanks, updated!

**Comment by ixti** [comment]
🙇

**Comment by ixti** [comment]
Yes via `HTTP::Response#uri`:

``` ruby
HTTP.follow.get("http://sensortower.com").flush.uri
# => #<HTTP::URI:0x0055947e0aaf60 URI:https://sensortower.com/>
```

**Comment by dkam** [comment]
Thanks - I've updated the wiki's redirect page.
