### ISSUE TITLE
SSL handshake_failure

### ISSUE THREAD

**Issue by nackep** [httprb/http#416]
SSL fails with latest http gem under jruby:

jruby-9.0.4.0 :031 > require "http"
 => true 
jruby-9.0.4.0 :032 > HTTP.get("https://blocktrades.us")
OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure
	from org/jruby/ext/openssl/SSLSocket.java:218:in `connect'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/timeout/null.rb:26:in `connect_ssl'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/timeout/null.rb:35:in `start_tls'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/connection.rb:158:in `start_tls'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/connection.rb:44:in `initialize'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/client.rb:60:in `perform'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/client.rb:41:in `request'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/chainable.rb:75:in `request'
	from /home/.rvm/gems/jruby-9.0.4.0/gems/http-2.2.2/lib/http/chainable.rb:19:in `get'
	from (irb):32:in `<eval>'
	from org/jruby/RubyKernel.java:978:in `eval'
	from org/jruby/RubyKernel.java:1291:in `loop'
	from org/jruby/RubyKernel.java:1098:in `catch'
	from org/jruby/RubyKernel.java:1098:in `catch'
	from /home/user/.rvm/rubies/jruby-9.0.4.0/bin/irb:13:in `<top>'

SSL is working:
https://www.sslshopper.com/ssl-checker.html#hostname=blocktrades.us

thank you heroes <3

**Comment by tarcieri** [comment]
Please file a bug here:

https://github.com/jruby/jruby-openssl
