### ISSUE TITLE
How to send a request with multiple identical keys

### ISSUE THREAD

**Issue by noraworld** [httprb/http#419]
Suppose we want to send the following request with query string parameters:

```
http://example.com/resource?id[]=1&id[]=2&id[]=3
```

We should probably use `HTTP.get()` like this:

```ruby
HTTP.get("http://example.com/resource", :params => {"id[]" => 1, "id[]" => 2, "id[]" => 3})
```

However, it's just not possible to have a hash with multiple identical keys in Ruby.

```ruby
irb(main):001:0> params = {"id[]" => 1, "id[]" => 2, "id[]" => 3}
(irb):1: warning: key "id[]" is duplicated and overwritten on line 1
(irb):1: warning: key "id[]" is duplicated and overwritten on line 1
=> {"id[]"=>3}
irb(main):002:0> params
=> {"id[]"=>3}
```

How should we do?

**Comment by noraworld** [comment]
Sending a request with indexes, I got an error.

### Request:
```ruby
HTTP.get("http://example.com/resource", :params => {"id[0]" => 1, "id[1]" => 2, "id[2]" => 3})
```

### Error:
```
/usr/local/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/mime_type.rb:37:in `[]': Unknown MIME type: text/html (HTTP::Error)
	from /usr/local/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/response.rb:141:in `parse'
	from ...
```

**Comment by britishtea** [comment]
To use multiple identical keys, use an Array of key-value tuples:

```ruby
HTTP.get "http://example.com/resource", :params => [["id",1], ["id",2], ["id", 3]]
```

The above error is unrelated (you're calling `#parse` without having registered a HTML parser). It does in fact make a request with the correct query string parameters (although the square brackets (`[` and `]`) are URL encoded).

**Comment by noraworld** [comment]
I tried, but an application server returned only result of the request with `id=3`.

I inspected what a request URL is:

```ruby
res = HTTP.get("http://example.com/resource", :params => [["id", 1], ["id", 2], ["id", 3]])
res.uri.to_s
=> "http://example.com/resource?id=1&id=2&id=3"
```

An application server doesn't work properly unless a request is like `http://example.com/resource?id[]=1&id[]=2&id[]=3`.

**Comment by noraworld** [comment]
I modified your solution a little like the following.

```ruby
res = HTTP.get("http://example.com/resource", :params => [["id[]", 1], ["id[]", 2], ["id[]", 3]])
res.uri.to_s
=> "http://example.com/resource?id%5B%5D=1&id%5B%5D=2&id%5B%5D=3"
# Decoded: "http://example.com/resource?id[]=1&id[]=2&id[]=3"
```

I tried above, and it worked properly.

Thanks to your suggestion I was able to solve the problem. I appreciate your help, @britishtea.
