### ISSUE TITLE
How to build a request without running it?

### ISSUE THREAD

**Issue by hmistry** [httprb/http#421]
There are 2 things I'd like to do with this library and not sure how to do it.

First, I'd like to print out the request to see if everything looks correct. I'm thinking something like `HTTP.headers(some_hash).get(some_url).to_s` which will create a string something like `GET some_url headers: some_headers`. With this I don't need to waste time with MiTM apps and can see the conversion is correct.

Second, I'd like to build a request without executing it. How can I do this? I couldn't find it in your docs/code. The reason is I need to create a signature token based on the request headers + body (it's for AWS). Having this ability would greatly simplify coding.

```ruby
#  (pseudo code for idea - ignore syntax correctness)
# current
headers = { some: values }
payload = something
content_size = payload.size
uri = some_url_with_params
signature = calculate_signature(headers.merge(content-length: content_size), payload, host_uri, params)
res = HTTP.headers(headers.merge(Authorization: signature).get(uri)

# my wish
request = HTTP.headers( some: values).build_request(:get, uri, { body: payload })
response = request.headers(Authorization: calculate_signature(request)).run
```
Hope this makes sense.

**Comment by ixti** [comment]
Logging interactions will be possible soon - I'm gonna find time next week to merge down outstanding PRs including logging one.

I like the proposal of `build_request` in fact I was thinking about that lately, as I needed the same for myself. Thus I'm totally open for PRs or will do that myself once will have some spare moments.

**Comment by rwehresmann** [comment]
The example of the issue should work? I'm trying:

```ruby
HTTP.headers({ accept: 'text/html' }).build_request('get', URI('https://www.google.ccom'))

NoMethodError: undefined method `build_request' for #<HTTP::Client:0x007f0904858338>
```

**Comment by tycooon** [comment]
Are you sure that you are using the version from master? It's not released on rubygems I guess.

**Comment by rwehresmann** [comment]
You're right, I didn't noticed that It wasn't in rubygems (: Tks!

**Comment by janko-m** [comment]
This has been implemented in https://github.com/httprb/http/pull/458.
