### ISSUE TITLE
Upgrade header which advertises protocol support being treated as an actual upgrading

### ISSUE THREAD

**Issue by unarist** [httprb/http#422]
from [RFC7230 sec. 6.7](https://tools.ietf.org/html/rfc7230#section-6.7):

> A server MAY send an Upgrade header field in any other response to advertise that it implements support for upgrading to the listed protocols, in order of descending preference, when appropriate for a future request.

However, current http.rb treats it as an actual upgrading, and doesn't process response body.

c.f. https://github.com/nodejs/http-parser/issues/363

**Comment by Gargron** [comment]
:+1:

**Comment by tarcieri** [comment]
Picking up the discussion from #508, hey @ixti, is #433 still the path forward on that?

Perhaps we should open an upstream issue about this on http_parser.rb (unless there already is one?)

**Comment by janko-m** [comment]
@tarcieri Considering that http_parser.rb doesn't work on JRuby 9.2.0.0, I think the path forward really is switching to `http-parser` gem. [http-protocol](https://github.com/socketry/http-protocol) also looks good, if we want pure Ruby.

**Comment by ixti** [comment]
Yeah. my plan was to switch to http-parser but with shim for it (I don't like it's API).

**Comment by tarcieri** [comment]
@ixti that's basically what you were working on in #433, right?

**Comment by ixti** [comment]
@tarcieri Yup!

**Comment by ixti** [comment]
I have cut 5.0.0 pre release version of gem with switch to updated http parser. This should be fixed now.
