### ISSUE TITLE
Timeout in production but not in development

### ISSUE THREAD

**Issue by twizzzlers** [httprb/http#425]
I'm running this simple code:

`HTTP.get('http://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/Cnpjreva_Solicitacao2.asp')`

In development where my Ruby version is 2.2.3 and Rails version is 4.2.6, it works.

But in production where my Ruby version is 2.3.4 and Rails version is 4.2.6, it does not work.
It keeps hanging until it gives me a Timeout Error:

`HTTP::ConnectionError: failed to connect: Connection timed out - connect(2) for "www.receita.fazenda.gov.br" port 80`

Am I doing something wrong? Or is this a ruby version bug?
Thank you!

**Comment by tarcieri** [comment]
This is likely an issue with either DNS or your production network.

Try this from a production shell (with netcat):

`$ nc -v www.receita.fazenda.gov.br 80`

**Comment by twizzzlers** [comment]
The issue was that `www.receita.fazenda.gov.br` blocked the ip from my production machine.
I just had to rebuild my AWS EBS for my instance to get a new ip. After this it worked.

Thank you for your help! :)
