### ISSUE TITLE
How to unescape comma on request?

### ISSUE THREAD

**Issue by AugustoEMoreira** [httprb/http#432]
I need to make a request where one gets parameter is a comma separated value, but i have a weird problem.
the f***ing server can't handle the encoded comma "%2C". How can i achieve this get?

Thanks

**Comment by ixti** [comment]
Right now the only way is to pass value as part of URI:

``` ruby
HTTP.get("http://localhost/?foo=1,2,3")
```

**Comment by ixti** [comment]
Just to clarify. Imagine you have following code:

``` ruby
HTTP.get("http://localhost:8080/foo?bar=1,2,3", :params => {
  :baz => "4,5,6"
})
```

It will issue the request:

```
GET /foo?bar=1,2,3&baz=4%2C5%2C6 HTTP/1.1
Connection: close
Host: localhost:8080
User-Agent: http.rb/2.2.2
Content-Length: 0
```

**Comment by AugustoEMoreira** [comment]
thanks for the answer
