### ISSUE TITLE
Which HTTP client gems use the Timeout library?

### ISSUE THREAD

**Issue by janko-m** [httprb/http#439]
In the [Thread Safety](https://github.com/httprb/http/wiki/Thread-Safety) wiki there is this paragraph:

> Unlike almost every other Ruby HTTP client (except native libraries like curl and EventMachine-based ones), this gem uses an asynchronous timeout backend which does not use the thread-unsafe timeout.rb library (except for DNS resolution, which can't be avoided without bypassing the system resolver). This means (except for the aforementioned DNS timeout usage) this gem provides advanced timeout.rb-free thread-safe timeout support which is not commonly found in other Ruby HTTP libraries, including Net::HTTP and all of its wrappers/derivatives.

However, Net::HTTP (and therefore HTTParty and REST Client) use the Timeout standard library only for opening the TCP connection, which HTTP.rb also does. I couldn't find any HTTP client gem which uses the Timeout standard library for setting timeouts on operations other than opening the TCP connection.

In that case should we remove this paragraph?

**Comment by tarcieri** [comment]
To my knowledge no other Ruby HTTP libraries provide a timeout system which
is both as advanced/flexible and thread safe.

Perhaps this section could be reworded to focus on the flexibility of the
timeout system, but I don’t think it should be removed outright.
-- 
Tony Arcieri

**Comment by tarcieri** [comment]
Also, are you actually sure about that? I’m on a phone and can’t look right
now, but the Timeout-based timeouts (previously?) used by Net::HTTP
occurred in protocol.rb
-- 
Tony Arcieri

**Comment by ixti** [comment]
I thought moving to socketry would allow us to get rid of using Timeout.

**Comment by tarcieri** [comment]
Socketry supports both the system resolver (using Timeout) and a Resolv-based resolver, which is asynchronous and doesn’t need Timeout, but implemented in pure Ruby and much less fully-featured.

The system resolver is the default.

**Comment by mikegee** [comment]
I don't see the thread-unsafe style timeouts in [protocol.rb](https://github.com/ruby/ruby/blob/trunk/lib/net/protocol.rb).

**Comment by zanker** [comment]
If I recall, Net::HTTP got fixed around 2.1-2.2 to not use Timeout.timeout.

The main advantage of httprb now is the overall timeout rather than per operation, which I don’t believe any others do.

**Comment by janko-m** [comment]
> To my knowledge no other Ruby HTTP libraries provide a timeout system which
> is both as advanced/flexible and thread safe.

I definitely agree!

> The main advantage of httprb now is the overall timeout rather than per operation, which I don’t believe any others do.

I agree, that's *really* useful, I also didn't see it in any other HTTP client libraries. Another thing is the `:write` timeout, which I imagine is really useful with file uploads (other libraries have only `:open/:connect` and `:read` timeouts).

**Comment by janko-m** [comment]
The reason why I asked about this paragraph is because in my recent HTTP.rb presentation I wanted to emphasize that HTTP.rb has *native* timeouts, and for comparison I wanted to mention a library that uses `Timeout.timeout` for write/read timeouts, but I couldn't find any (I didn't see any non-thread-safety in `Net::HTTP`). While native timeouts are objectively a cool feature, it seems to me that other HTTP libraries have caught up as well, so I wanted to check if the paragraph didn't get outdated.

**Comment by janko-m** [comment]
I removed the outdated `timeout.rb` paragraph from the "Thread-Safety" wiki page. I agree that http.rb's timeout system is advanced compared to alternatives, so anyone is free to extend the "Timeouts" wiki page with more information.
