### ISSUE TITLE
Documentation on handling exceptions/timeouts?

### ISSUE THREAD

**Issue by nightsurge** [httprb/http#440]
Hello,

The documentation has no details on how to handle request exceptions and timeouts. A small blurb would be wonderful so that we know how to properly rescue without being overly generic (rescue => e).

Thanks!

**Comment by mikegee** [comment]
Documentation on this sounds like a great idea. I think the answers you are looking for are in [http/errors.rb](https://github.com/httprb/http/blob/master/lib/http/errors.rb).

**Comment by febeling** [comment]
Or more generally put: which conditions and status are returned as responses, and which raise exceptions. That documentation doesn't make that obvious.

**Comment by ixti** [comment]
If request was sent and response received, there will be no exception regardless of response HTTP status. So the only exceptions you might expect are really bad things.

To catch bad things occurred during connection/request/response stages you might rescue from `HTTP::Error` or any of the errors from the list @mikegee provided. All other exceptions that might be raised are basically unrecoverable runtime errors (e.g. wrong arguments/types).

**Comment by febeling** [comment]
@ixti Thanks, great answer.

I really like the brevity in which the philosophy is explained. I've taken the liberty to cast it into a basic wiki page [Errors and Exceptions](https://github.com/httprb/http/wiki/Errors-and-Exceptions), hoping that is welcome.

**Comment by febeling** [comment]
There are now wiki pages documenting [Timeouts](https://github.com/httprb/http/wiki/Timeouts) and about [Errors and Exceptions](https://github.com/httprb/http/wiki/Errors-and-Exceptions).

So I think it would be OK to close the issue now.

**Comment by ixti** [comment]
@febeling thank you.
