### ISSUE TITLE
Ability to makes calls to SSL endpoing with invalid cert

### ISSUE THREAD

**Issue by nightsurge** [httprb/http#442]
I realize this is an unsafe thing, but the ability to override or pass in an option to ignore SSL errors when making an https call to a server with invalid cert would be very helpful.

In my case, the server is only ever accessed internally, but for some reason uses HTTPS and has an invalid cert. I found this option in Net::HTTP but saw no similar option in HTTP.rb:
`verify_mode: OpenSSL::SSL::VERIFY_NONE`
https://stackoverflow.com/a/9837520/4167402

**Comment by ixti** [comment]
You can pass [custom `ssl_context`](https://github.com/httprb/http/wiki/HTTPS). So in your case it will look like:

``` ruby
ctx = OpenSSL::SSL::SSLContext.new
# ...
ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE

HTTP.get("https://www.google.com", :ssl_context => ctx)
```

**Comment by ixti** [comment]
Pressed wrong button :D

Please close if the answer solves your issue.

**Comment by tarcieri** [comment]
This has come up enough times (#308, #354) I wonder if it would be better to have an obvious, easily greppable way to do this

**Comment by zanker** [comment]
Do we have something in the docs? If I recall, the original intent was to make it harder to bypass security essentially.

**Comment by nightsurge** [comment]
@ixti this does resolve my issue, thanks! But I'll leave open to allow the rest of the discussion to finish in case any documentation work is needed.

**Comment by tarcieri** [comment]
I added a section to the Wiki about this, hopefully with enough scary language to encourage people not to do it: https://github.com/httprb/http/wiki/HTTPS#disabling-certificate-verification-ie-insecure-usage
