### ISSUE TITLE
More convenient timeout

### ISSUE THREAD

**Issue by kenn** [httprb/http#444]
As much as I absolutely appreciate to have the flexibility of connect/write/read timeouts separately, sometimes it makes sense to have a simpler form:

```ruby
HTTP.timeout(5).get
```

as a drop-in replacement for:

```ruby
Timeout.timeout(5) { YourHttpTool.get }
```

which maintains parity with the original semantics, thus enable to migrate from other tools.

Is this something we're interested?

**Comment by ixti** [comment]
I was thinkign about this recently in fact. As we have shorthand syntax for `:per_operation` ( when you pass hash directly) I thought it will be reasonable to decide that timeout is `:global` when Integer is given.

**Comment by vincentwoo** [comment]
I agree, and was surprised to find that global did not work this way.
