### ISSUE TITLE
Noticing "warning: method redefined; discarding old ..." warnings

### ISSUE THREAD

**Issue by javierjulio** [httprb/http#445]
When running tests for a gem that uses http 3.0, I'm seeing the following warnings:

```
/Users/javierjulio/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/http-3.0.0/lib/http/options.rb:107: warning: method redefined; discarding old features=
/Users/javierjulio/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/http-3.0.0/lib/http/options.rb:128: warning: method redefined; discarding old follow=
/Users/javierjulio/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/http-3.0.0/lib/http/options.rb:138: warning: method redefined; discarding old persistent=
```

I'm not sure why they are occurring. I figure it had to do with my setup but I'm not sure what could be causing it since I don't do anything in regards to those options. If there is any more helpful info I can provide, let me know.

**Comment by javierjulio** [comment]
Apologies, I thought this was just with upgrading to http v3 but even on v2.2.1 I'm noticing it.

**Comment by javierjulio** [comment]
We recently updated Ruby from 2.3.1 to 2.4.2. Since I'm noticing this on http v2.x as well, likely that its related to Ruby 2.4.x?

**Comment by ixti** [comment]
Hmm. We need to fix `HTTP::Options`.
