### ISSUE TITLE
Newline "\n" is encoded as "%0D%0A" in query string values

### ISSUE THREAD

**Issue by vassilevsky** [httprb/http#449]
Hello 🙂

I use version 2.2.2 but the code seems to be the same in 3.0.0 as well.

I noticed that newlines `\n` are encoded as `\r\n` in query string:

```
 ~    ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
 ~    irb
irb(main):001:0> require 'http'
=> true
irb(main):002:0> HTTP::VERSION
=> "2.2.2"
irb(main):003:0> require 'httplog'
=> true
irb(main):004:0> HTTP.get('http://example.com', params: {foo: "bar\nbaz"})
D, [2018-01-15T19:25:37.641493 #66440] DEBUG -- : [httplog] Sending: GET http://example.com/?foo=bar%0D%0Abaz
```

This is because the params are put through `Addressable::URI.form_encode`, which replaces everything with `\r\n`:

https://github.com/httprb/http/blob/c69844911b74472bd40a9979fa452bff6c179045/lib/http/client.rb#L126

I think that this behavior is incorrect. It is also unexpected. Query string values are not form values.

For example, ActiveSupport simply encodes `\n`:

```
irb(main):001:0> require 'active_support/core_ext/object/to_query'
=> true
irb(main):002:0> {foo: "bar\nbaz"}.to_query
=> "foo=bar%0Abaz"
```

**Comment by mikegee** [comment]
Rack behaves like ActiveSupport on this. (ActiveSupport might delegate to Rack):

```ruby
Rack::Utils.build_nested_query(foo: "bar\nbaz")
#=> "foo=bar%0Abaz"
```

Looks like `http` is actually delegating to Addressable here:

https://github.com/httprb/http/blob/c69844911b74472bd40a9979fa452bff6c179045/lib/http/uri.rb#L45-L47

We can use Addressable differently to get the expected behavior:

```ruby
uri = Addressable::URI.new
uri.query_values = { foo: "bar\nbaz" }
uri.query
#=> "foo=bar%0Abaz"
```
