### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by RobinClowers** [httprb/http#480]
I've just started using this gem on a small side project, and I really like it so far, thanks for all the hard work! That said, the documentation seem pretty thin on basics like using the chainable api and simple examples like making a post request with a body. I was able to figure these things out by reading the code, but would you be open to a small contribution to improve this? I was thinking maybe expanding the readme with some basic examples, but also possibly some high level module docs?

**Comment by tarcieri** [comment]
A lot of the present documentation is in the Wiki:

https://github.com/httprb/http/wiki

Posting a request with the body is documented here:

https://github.com/httprb/http/wiki/Passing-Parameters

That said I know people have had trouble discovering this documentation.

A few things I think would be good:

1) Make the documentation links to the Wiki more obvious. Maybe don't even mention they're a Wiki until people get there, as people seem afraid of Wikis (ours is contributor-only)
2) Improve Yard documentation

Sounds like you want to work on number 2?

**Comment by RobinClowers** [comment]
Well that's odd, I swear I remember clicking on the wiki and finding it nearly empty, but clearly I'm mistaken. The wiki is exactly the sort of documentation I was looking for, and I don't really see a need to reproduce that sort of high level documentation in the Yard docs. Thanks for the quick response!

**Comment by tarcieri** [comment]
I added a more obvious "Documentation" link in #481
