### ISSUE TITLE
undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by tycooon** [httprb/http#484]
I guess this error happens when server returns some invalid response. Would be really cool to raise `HTTP::ConnectionError` in such cases.

```
A NoMethodError occurred in background at 2018-06-21 10:22:03 UTC :

 undefined method `join' for nil:NilClass
 <...>/ruby/2.5.0/gems/http-3.3.0/lib/http/response/parser.rb:23:in `http_version'
 <...>/ruby/2.5.0/gems/http-3.3.0/lib/http/client.rb:76:in `perform'
```

**Comment by tarcieri** [comment]
Relevant method is here:

https://github.com/httprb/http/blob/master/lib/http/response/parser.rb#L22

Curious to know what the HTTP response looked like...

**Comment by tycooon** [comment]
I guess something like empty response. The thing is, that method might return `nil`, so using `join` there is not cool. See https://github.com/tmm1/http_parser.rb/blob/master/ext/ruby_http_parser/ruby_http_parser.c#L413

**Comment by mikegee** [comment]
I can say that I've seen this error too. Unfortunately, I don't recall the exact context and I can't find occurrences in our error tracking system anymore.

**Comment by tatey** [comment]
I'm also encountering this exception. I put in a debugger to see if I could work out what's going on.

``` ruby
# https://github.com/httprb/http/blob/master/lib/http/response/parser.rb#L22
def http_version
  begin
    @parser.http_version.join(".")
  rescue NoMethodError => error
    byebug
    raise
  end
end
```

And when the exception is raised this is the state of the object.

```
(byebug) self
#<HTTP::Response::Parser:0x00007fed1cb0fc00 @parser=#<HTTP::Parser:0x00007fed1cb0fb60>, @finished=false, @headers=nil, @chunk=nil>
```

I'm occasionally seeing other exceptions like:

```
[ActiveJob] [Basecamp3RobinJob] [a5012d6b-ca72-43a0-95bf-6f42b3adac59] Error performing Basecamp3RobinJob (Job ID: a5012d6b-ca72-43a0-95bf-6f42b3adac59) from Async(default) in 1242.55ms: HTTP::ConnectionError (error reading from socket: Bad file descriptor):
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/timeout/per_operation.rb:81:in `wait_readable'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/timeout/per_operation.rb:81:in `block in readpartial'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/timeout/per_operation.rb:64:in `loop'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/timeout/per_operation.rb:64:in `readpartial'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/connection.rb:216:in `read_more'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/connection.rb:103:in `block in read_headers!'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/connection.rb:102:in `loop'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/connection.rb:102:in `read_headers!'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/client.rb:71:in `perform'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/client.rb:30:in `request'
/Users/Tate/.gem/ruby/2.5.1/gems/http-3.3.0/lib/http/chainable.rb:20:in `get'
```

Which I feel like is probably related. Any ideas?

**Comment by tatey** [comment]
Ah, I think I found the source of my problem. I'm writing an API wrapper where `HTTP::Client` is an attribute. I'm calling `#dup` on the the wrapper and those instances must have been using a stale IO? Anyway, I solved by implementing #initialize_dup:

``` ruby
    def initialize_dup(other)
      super
      @http = HTTP::Client.new(other.http.default_options)
    end
```

**Comment by ixti** [comment]
I have cut 5.0.0 pre release version of gem with switch to updated http parser. @tycooon can you please confirm if that fixes the problem?

**Comment by tycooon** [comment]
Thanks, I will try to test it tomorrow.

**Comment by tycooon** [comment]
I didn't notice any of these errors in pre release, so I'm closing the issue now 👍
