### ISSUE TITLE
readpartial sometimes returns empty string

### ISSUE THREAD

**Issue by jrochkind** [httprb/http#485]
Not nil that means it's over, but the empty string. At first I thought it never did this twice in a row, but I believe it actually can. 

Not totally sure if this is a bug or not -- maybe it's expected?  But if I'm trying to wrap things in an "IO-like" duck-typed API, that converst `read` calls to `readpartial` on the body... some consumers that want an "IO-like" object don't ever expect `read(some_bytes)` to return the empty string. I don't believe ruby native IO objects ever will, for instance. 

Is this a bug? And in what circumstances might readpartial return empty string?

**Comment by jrochkind** [comment]
This applies to `each` too actually. 

If I do `each` on a #body, sometimes it yields an empty string.

**Comment by tarcieri** [comment]
Could this be related to #422?

**Comment by ixti** [comment]
I have cut 5.0.0 pre release version of gem with switch to updated http parser. This should be fixed now.
