### ISSUE TITLE
Tracking read/write/connect metrics in the gem

### ISSUE THREAD

**Issue by zanker** [httprb/http#492]
I'm going to see about using HTTP for solving something at work, and one thing I need is the ability to breakout metrics into time spent in read vs write vs connect for tuning timeouts. I've not really seen another gem provide that before, but seems useful to me.

My thought would be they just live as a method similar to `body` or `headers`, that provides the summary of the last request made on that instance of the client. 

Any particular objections to me adding that?

**Comment by ixti** [comment]
Probably we can have it as a feature (recent changes into features injection makes it pretty possible IMO - just need another method like `wrap_connection`).

I don't have any objection in general, but would like it not affect default usage. Although I realize adding such metrics into default flow won't make significant impact. So I would be really happy to know what others think.

@httprb/core chip in!

**Comment by zanker-stripe** [comment]
That means you'd get `post_connection_check` as part of the metrics on connect time which isn't what I'd want. It would purely be the time spent in IO, which means we'd need some kind of `wrap_timeout` which I think is overkill. Not really a fan of wrapping the entire IO object to get timing metrics, as it essentially means we're duplicating a bunch of code/data to get a slight separation of concerns.

**Comment by ixti** [comment]
As I said, I have no strong feelings one way or the other.

The only thing that annoys me is that this means we will add some debug metrics into core functionality that will be used by one-two persons only. In addition to that, some people (e.g. me) might have weird idea that using `Time.now` is bad and that monotonic time should be used instead...

**Comment by tarcieri** [comment]
For what it's worth, the [timeout subsystem in the not-quite-finished Socketry gem](https://github.com/socketry/socketry/blob/master/lib/socketry/timeout.rb) was based on monotonic time (via `HiTimes`, although it seems Ruby has native support now).

**Comment by zanker** [comment]
Nice. Thanks! Think we can close this out for now.
