### ISSUE TITLE
A problem of sending requests after recovery Internet connection

### ISSUE THREAD

**Issue by yuryroot** [httprb/http#495]
Hi, gem's maintainers!
Thank you for really awesome gem!

I have some problems with sending requests after the internet connection disappeared/appeared.

**My environment:**
* Ruby version is `2.5.0p0`
* HTTP.rb version is `3.3.0`
* OS is `Linux Fedora 25`

Please consider 2 examples:

**First example** (works as expected)

```ruby
[yury@pc ~]$ irb
2.5.0 :001 > require 'http'
 => true 

# Here the Internet connection is established

2.5.0 :002 > HTTP.get('https://google.com')
 => #<HTTP::Response/1.1 301 Moved Permanently {"Location"=>"https://www.google.com/", "Content-Type"=>"text/html; charset=UTF-8", "Date"=>"Tue, 07 Aug 2018 08:49:39 GMT", "Expires"=>"Thu, 06 Sep 2018 08:49:39 GMT", "Cache-Control"=>"public, max-age=2592000", "Server"=>"gws", "Content-Length"=>"220", "X-Xss-Protection"=>"1; mode=block", "X-Frame-Options"=>"SAMEORIGIN", "Alt-Svc"=>"quic=\":443\"; ma=2592000; v=\"44,43,39,35\"", "Connection"=>"close"}> 

# Here the Internet connection was disabled

2.5.0 :003 > HTTP.get('https://google.com')
Traceback (most recent call last):
       11: from /home/yury/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
       10: from (irb):3
        9: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/chainable.rb:20:in `get'
        8: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/chainable.rb:77:in `request'
        7: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:30:in `request'
        6: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:67:in `perform'
        5: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:67:in `new'
        4: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/connection.rb:43:in `initialize'
        3: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `connect'
        2: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `open'
        1: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `initialize'
HTTP::ConnectionError (failed to connect: getaddrinfo: Name or service not known)

# Here the Internet connection was enabled

2.5.0 :004 > HTTP.get('https://google.com')
 => #<HTTP::Response/1.1 301 Moved Permanently {"Location"=>"https://www.google.com/", "Content-Type"=>"text/html; charset=UTF-8", "Date"=>"Tue, 07 Aug 2018 08:49:49 GMT", "Expires"=>"Thu, 06 Sep 2018 08:49:49 GMT", "Cache-Control"=>"public, max-age=2592000", "Server"=>"gws", "Content-Length"=>"220", "X-Xss-Protection"=>"1; mode=block", "X-Frame-Options"=>"SAMEORIGIN", "Alt-Svc"=>"quic=\":443\"; ma=2592000; v=\"44,43,39,35\"", "Connection"=>"close"}> 
```

In the example above, I sent first HTTP request to Google and then turned off the Internet connection.
Second HTTP request was failed (there was no internet connection).
Finally, before sending last HTTP request I turned on the Internet connection so request was successfully sent.

All is good in this example.
The problem occurs in the second example.

**Second example** (unexpected behaviour)

In previous example I sent HTTP connection before the Internet connection was turned off.
But in this example I will disable the internet connection before sending the first HTTP request.

```ruby
[yury@pc~]$ irb
2.5.0 :001 > require 'http'
 => true 

# Here the Internet connection was disabled

2.5.0 :002 > HTTP.get('https://google.com')
Traceback (most recent call last):
       11: from /home/yury/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
       10: from (irb):2
        9: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/chainable.rb:20:in `get'
        8: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/chainable.rb:77:in `request'
        7: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:30:in `request'
        6: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:67:in `perform'
        5: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:67:in `new'
        4: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/connection.rb:43:in `initialize'
        3: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `connect'
        2: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `open'
        1: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `initialize'
HTTP::ConnectionError (failed to connect: getaddrinfo: Name or service not known)

# Here the Internet connection was enabled, but all HTTP all requests will fail

2.5.0 :003 > HTTP.get('https://google.com')
Traceback (most recent call last):
       11: from /home/yury/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
       10: from (irb):3
        9: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/chainable.rb:20:in `get'
        8: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/chainable.rb:77:in `request'
        7: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:30:in `request'
        6: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:67:in `perform'
        5: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/client.rb:67:in `new'
        4: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/connection.rb:43:in `initialize'
        3: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `connect'
        2: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `open'
        1: from /home/yury/.rvm/gems/ruby-2.5.0/gems/http-3.3.0/lib/http/timeout/null.rb:21:in `initialize'
HTTP::ConnectionError (failed to connect: getaddrinfo: Name or service not known)
```

The problem is that after connection recovery, in this case, all HTTP requests will fail.

**UPDATED**

I've checked this issue on Ubuntu 16.04.
There is no such problem on that OS.

**Comment by tarcieri** [comment]
This looks like a dupe of #459 and #420. Perhaps we should make an issue specific to an automatic retry feature

**Comment by tarcieri** [comment]
Well, I think it's a more general symptom of people expecting this library to gracefully tolerate network failures when using persistent connections. In the issues I've linked there's been some discussion of adding an auto-retry feature (similar to browser behavior)

**Comment by ixti** [comment]
@tarcieri I understood that. My point was that this particular issue is even less relevant to http gem than those two issues. I remember I had similar issues with firefox. Which I believe was related to NetworkManager's resolver in fact, rather than browser itself - it was caching failures for pretty long, so I had to restart it.

**Comment by ixti** [comment]
@yuryroot try to check will that issue be still reproducible on fedora 25 if after network went up back you will restart network manager. Or something like that.

**Comment by yuryroot** [comment]
@ixti the problem is still reproducible after restarting the network manager. I also don't use persistent connections.

I've checked a problem deeper so it looks that it's a problem of ruby, as you said above.
Under the hood, HTTP.rb uses `TCPSocket.open` to establish the connection which uses `Addrinfo.getaddrinfo` to get necessary info for domain (IP and some other).

So this problem is the issue of `Addrinfo.getaddrinfo` stdlib's method of ruby on Fedora 25.

**Comment by ixti** [comment]
@yuryroot Yeah. I was going to say that it might be getaddrinfo of ruby, but I love ruby too much, so decided to blame Fedora Linux first ;))

**Comment by tarcieri** [comment]
@ixti oh sorry, I missed it was a DNS error (the stack traces with the exception at the bottom still kind of freak me out). Also I'm not much of a NetworkManager and disable it on all my servers 😉 

@yuryroot that error is ultimately a libc error, although looking at the Ruby bug tracker, it seems it might be hiding deeper errors like file descriptor leaks:

https://bugs.ruby-lang.org/issues/11600
