### ISSUE TITLE
Revisisting rescoping `HTTP` base class?

### ISSUE THREAD

**Issue by zanker** [httprb/http#497]
Given we have a breaking 4.0 coming, thoughts on revisiting the `HTTP` class name? We could do it as changing it to `HTTPRb` with an alias to `HTTP` then in 5.0 drop the alias. I believe we discussed this a year or two ago.

Got bit by the generic `HTTP` bit because `HTTPClient` uses it too (although on `HTTP::Message`) and some internal infra conflicts. It's also just generally not great that it's so generic since it's easy for other people to use the same namespace.

I can do the PR if we're interested in this being a 4.0 change.

**Comment by zanker** [comment]
Alternatively, we could just offer it as a compatibility mode and do it under 3.0. Class is renamed to `HTTPRb`, but we require `http/compatibility` by default which sets the alias.

(Tip to @brandur-stripe who suggested it)

**Comment by tarcieri** [comment]
What specific problem is this causing, and would it be possible to work with the other gems which are conflicting to correct it?

**Comment by zanker** [comment]
In this case, `HTTPClient` is unmaintained for 2 years so not really. I don't think it's great to use such a common base class name though, it's not impossible someone else could write a gem or have internal code that uses the same class named `HTTP`.

Since it's Ruby, you don't really have any way of noticing it until something breaks due to conflicts.

**Comment by tarcieri** [comment]
Is the problem just that other gems define a module called `HTTP`?

**Comment by ixti** [comment]
I agree that HTTP is pretty generic namespace, but we are the HTTP gem, pretty generic HTTP client in Ruby ;)) And why should we change our namespace (when gem name is pretty clear: `http`) just because of others using our namespace? :D

**Comment by r-obert** [comment]
as far as writing nice code goes, `HTTPrb` is not as elegant as just `HTTP`. i also think that, given it is the `http` gem, it has exclusive rights to the `HTTP` namespace, following the convention that gem names match at least a module or class name... it's the case most of the time.

**Comment by zanker** [comment]
:shrug:

I won't push the point since others don't feel the same. I'd argue it's the equivalent to if I made a gem called `Coords`, `Windows` or `User`, it's similarly encroaching on a generic namespace that's not guaranteed to be yours.
