### ISSUE TITLE
Semicolon in path segement and Puma

### ISSUE THREAD

**Issue by Bonias** [httprb/http#501]
I have simple rack app and use puma to run it:

```
→ cat config.ru 
class App
  def self.call(env); [200, {}, []]; end;
end
run App

→ rackup -s puma config.ru
```

Let's try to make request that includes semicolon in the path:

```
HTTP.request(:get, 'http://localhost:9292/x;y')
=> #<HTTP::Response/1.1 200 OK {"Transfer-Encoding"=>"chunked", "Connection"=>"close"}>
```

in the puma logs `;y` is missing:

```
::1 - - [27/Sep/2018:15:43:52 +0200] "GET /x HTTP/1.1" 200 - 0.0004
````

I found Puma issue for this https://github.com/puma/puma/issues/1122 and they claim "Puma's doing the right thing" and "It should probably be encoded as %3B to work". So let's try to encode semicolon:

```
HTTP.request(:get, 'http://localhost:9292/x%3By')
```

and the result is exactly the same:

```
::1 - - [27/Sep/2018:15:46:25 +0200] "GET /x HTTP/1.1" 200 - 0.0004
```

it's because `http` (or more precisely `addressable`) normalize `http://localhost:9292/x%3By` to `http://localhost:9292/x;y` before sending request.

What's your thought on it?

**Comment by ixti** [comment]
I'm not sure why Puma devs are saying it's right thing. If I understand URI spec correctly `;` is valid to be as-is in path:

```
      path          = path-abempty    ; begins with "/" or is empty
                    / path-absolute   ; begins with "/" but not "//"
                    / path-noscheme   ; begins with a non-colon segment
                    / path-rootless   ; begins with a segment
                    / path-empty      ; zero characters

      path-abempty  = *( "/" segment )
      path-absolute = "/" [ segment-nz *( "/" segment ) ]
      path-noscheme = segment-nz-nc *( "/" segment )
      path-rootless = segment-nz *( "/" segment )
      path-empty    = 0<pchar>
      segment       = *pchar
      segment-nz    = 1*pchar
      segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
                    ; non-zero-length segment without any colon ":"

      pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
```

```
      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

**Comment by ixti** [comment]
I think puma is using old RFC :D

**Comment by ixti** [comment]
Regardless of what puma's doing I think we should provide a way for URIs to bypass normalization

**Comment by tarcieri** [comment]
An `Option` to shut it off would be nice. Ditto for the header mangling in #337

**Comment by jmchambers** [comment]
**Reposting my comment from puma/puma#1122 here...**

---

Sir Tim Berners-Lee uses semicolons in his ["Matrix URI" proposal](https://www.w3.org/DesignIssues/MatrixURIs.html), and while they're not _widely_ used, [Angular 2 adopted them](https://angular.io/guide/router#heroes-list-optionally-selecting-a-hero), and [Apigee recommend using them in REST APIs](https://cloud.google.com/files/apigee/apigee-web-api-design-the-missing-link-ebook.pdf). Here's an example:

`/people;name=jon/dogs;color=brown;size=medium?page=2`

So I'm pretty sure the use of unescaped semicolons _is_ valid when they're used as delimiters for parameters defined in the path. If they're used for any other purpose, then they should be escaped:

`/attachments;name=attachment-with-%3B-semicolon.txt`

There's a good discussion about this here:

https://stackoverflow.com/questions/2048121/url-matrix-parameters-vs-request-parameters

Puma chops off the path at the first semicolon, and so parses the above examples as:

`/people`
`/attachments`

I can confirm that both WEBrick and Thin parse these correctly, and so I would say this is a bug that needs fixing in Puma.

**Comment by dentarg** [comment]
> Regardless of what puma's doing I think we should provide a way for URIs to bypass normalization if user wants so.

Was this solved by https://github.com/httprb/http/commit/7fd135648f7d48b6a246d303ce9e0cc5aabfba57? Looks like this issue can be closed?

**Comment by ixti** [comment]
Puma was [fixed](https://github.com/puma/puma/pull/1934) around end of August. So puma-4.3.0 should work just fine with default normalizer. As of http-4.1.0 you can also provide custom URL normalizer of your own:

``` ruby
uri_normalizer = proc { |uri| uri.to_s }
HTTP.use(:normalize_uri => {:normalizer=>uri_normalizer}).get(...)
```

So, yes, I think this can be closed now.
