### ISSUE TITLE
can't follow 302 found redirect?

### ISSUE THREAD

**Issue by memorable111** [httprb/http#507]
consider the following script
```
require 'http'
brute=gets
response = HTTP.follow.post('http://zero.webappsecurity.com/signin.html', :params => {:user_login=>"admin",:user_password=>"#{brute}", :submit=>"Sign+in"} )
puts response.to_s
```
now the website should give me a 302 redirect and httprb should follow it 
but i am getting the following error:
```
/var/lib/gems/2.3.0/gems/http-4.0.0/lib/http/redirector.rb:91:in `redirect_to': can't follow 302 Found redirect (HTTP::StateError)
	from /var/lib/gems/2.3.0/gems/http-4.0.0/lib/http/redirector.rb:61:in `perform'
	from /var/lib/gems/2.3.0/gems/http-4.0.0/lib/http/client.rb:34:in `request'
	from /var/lib/gems/2.3.0/gems/http-4.0.0/lib/http/chainable.rb:27:in `post'
	from a.rb:3:in `<main>'
```

**Comment by ixti** [comment]
@tarcieri that's what `:strict => false` is for :D We can change `:strict` default value to be `false` though.

**Comment by tarcieri** [comment]
@ixti it's a bit different from just that I think? The particular behavior documented above 302 redirects a `POST` to a `GET`

**Comment by ixti** [comment]
@tarcieri Yes, that's what `:strict => false` does:

https://github.com/httprb/http/blob/master/lib/http/redirector.rb#L90-L93

Basically logic is following:

- if `VERB` is `POST`, `PUT` or `DELETE`
  - and redirect `CODE` is `300`, `301` or `302`
    - and `STRICT` is `true` then raise StateError
    - else change `VERB` to `GET` and follow redirect

**Comment by tarcieri** [comment]
My bad!

**Comment by memorable111** [comment]
Thanks! it works now
