### ISSUE TITLE
How to condition requests logging?

### ISSUE THREAD

**Issue by bobmaerten** [httprb/http#509]
Hi,

I'd like log HTTP requests only in development environment. So for now, I'm using something like that for each request throughout my app:

```ruby
req = HTTP.follow.timeout(5)
req = req.use(logging: { logger: Rails.logger }) if Rails.env.development?
req.get("https://github.com/")
```

Having to deal with quite some requests everywhere, I'd like to set an initializer to condition HTTP logging globally but I can't figure how to do it reading feature/instrumentation code.

What's the proper way to register the logging feature only in dev?

**Comment by paul** [comment]
In our app, I set up a file in lib to make a custom HTTP client class:

```ruby
module Tesseract
  HTTP =
    ::HTTP
    .timeout(connect: 2.seconds, read: 10.seconds, write: 10.seconds)
    .use(logging: { logger: Rails.logger })
end
```

Then, anywhere we need an http client, we can just call `Tesseract::HTTP.get("https://github.com/")` instead of the base HTTP. You can do something similar to set up the logger however you need to in your own app.

**Comment by bobmaerten** [comment]
Nice trick! Reminds me of minitest before(:all)-like trick (https://github.com/seattlerb/minitest#how-to-run-code-before-a-group-of-tests).

Thx @Paul.
