### ISSUE TITLE
HTTP.get not always returning response body

### ISSUE THREAD

**Issue by arjunrajkumar** [httprb/http#523]
Saw the examples - and `HTTP.get("https://github.com").to_s` returns the pages HTML.

But trying with a few other websites and its only returning a string. 

e.g. `HTTP.get("https://www.irepair.in/").to_s` or  `HTTP.get("https://www.wiinnova.com/").to_s` returns empty string. 

Just wondering if i'm missing something - or this works on some websites. 

Any advice on how to fix this? Thanks.

**Comment by arjunrajkumar** [comment]
Thanks 🙏

**Comment by arjunrajkumar** [comment]
> I'm gonna cut 5.0.0-alpha1 gem this weekend with changes in master

Hey.. Just checking if updates on this. Whenever you get the time. Thanks!

**Comment by tarcieri** [comment]
This is a dup of #485. Please see the status update there.
