### ISSUE TITLE
HTTP Pipelining?

### ISSUE THREAD

**Issue by dgollahon** [httprb/http#528]
I was wondering if HTTP is planning to support HTTP pipelining at any point. I found some references to "paving the way" for this feature (i.e. https://github.com/httprb/http/pull/39) but no obvious implementation or recent discussion. Is this something that is on the roadmap at all? I'd much prefer to use HTTP for all my web requests, but for a specific use case I think I may end up switching one of my tools to [net-http-pipeline](https://github.com/drbrain/net-http-pipeline) to take advantage of persistent connections and pipelining instead of just the persistent connections that HTTP offers.

Regardless, thanks for a great tool.

**Comment by tarcieri** [comment]
I originally implemented pipelining in Reel, a web server based on the same HTTP parser:

https://github.com/celluloid/reel

In my opinion, HTTP pipelining was a mistake, the end result of which is HTTP/2, which I consider a significantly better approach.

Implementing HTTP pipeline added considerable complexity both to the implementation and to the API ergonomics.

[We already have people confused by streaming support](https://github.com/httprb/http/issues/522), and HTTP pipelining just adds another dimension to the complexity.

I don't want to rule it out, but I would like to point out that it comes at a high cost in terms of code and API complexity, and IMO provides relatively little value.

**Comment by dgollahon** [comment]
Thanks for the extra background.

In my case I am trying to connect with an external API which supports HTTP/1.1 with pipelining but does not support HTTP/2. I need to issue a variable number of requests to the API during the lifecycle of a request on one of our servers so I'm trying to see how much I can optimize the total response time.

I think my other option would be to just keep several persistent connections open and check out a couple of those and issue multiple requests asynchronously during our request lifecycle. I haven't done any benchmarks yet to compare the approaches, but it seemed like pipelining was a clear fit for my situation, though not something HTTP.rb supported (and I'm otherwise happy with HTTP.rb). I may be overthinking this though and do just as well with the pool of persistent connections. I probably just need to try both and measure them in production.

I can certainly respect wanting to keep code and API complexity at a minimum.

**Comment by HoneyryderChuck** [comment]
In the ruby ecosystem, besides `net-http-pipeline` which you already mentioned, [httpx also support pipelining](https://gitlab.com/honeyryderchuck/httpx#concurrency), while supporting almost the same API as `httprb`. Assuming that you have your code already with `httprb` syntax and don't want to rewrite it to fit net-http, and no one is going to implement pipelining in `httprb` soon, I'd recommend you give it a try.

I'm httpx's maintainer, btw.

**Comment by ixti** [comment]
I totally agree with @tarcieri that it will complicate things a lot (at least I don't see easy way without rewriting like the vast majority of internals and make new code easy to understand and maintain).

I think you really can get around same results (if not better) without using pipelines by using pool of persistent connections as you mentioned.

**Comment by dgollahon** [comment]
Ok, thanks guys. I think @ixti and @tarcieri have convinced me it wouldn't be a good fit for `httprb`, so I'll just go ahead and close this.

@HoneyryderChuck I will check out `httpx`, thanks!
