### ISSUE TITLE
Do not rewind unrewindable IOs

### ISSUE THREAD

**Issue by ixti** [httprb/http#531]
[Reported](https://github.com/httprb/http/pull/468#issuecomment-463596941) by @mikker:

---

We're using `IO.pipe` for chunked POST requests in @elastic's [APM Agent](https://github.com/elastic/apm-agent-ruby) and I'm stubbing away rewind on my reader objects because of this.

```ruby
# HTTP.rb calls #rewind the body stream which IO.pipes don't support
class ModdedIO < IO
  def self.pipe(ext_enc = nil)
    super(ext_enc).tap do |rw|
      rw[0].define_singleton_method(:rewind) { nil }
    end
  end
end
```

Just wanted to provide an actual use of IO.pipe.

**Comment by janko** [comment]
@ixti The issue is that `IO.pipe` objects still respond to `#rewind`, but they fail if you try to call it.

I personally don't think that http.rb shouldn't attempt to do any rewinding, precisely because some IO objects are not rewindable. But I'd like to hear what others think.

**Comment by ixti** [comment]
Oh. Right. Because `IO.pipe` returns 2 `IO` objects in fact... So, probably we should do something like:

``` ruby
def ignorant_rewind(io)
  io.rewind if io.respond_to? :rewind
rescue Errno::ESPIPE
  nil
end
```

**Comment by janko** [comment]
Yes, that would be a good fix for pipes.

**Comment by ixti** [comment]
I think the same should be implemented for http/form_data as well.

**Comment by mikker** [comment]
Solves my case perfectly ❤️
