### ISSUE TITLE
Empty body

### ISSUE THREAD

**Issue by amerov** [httprb/http#534]
```
res = HTTP.get('https://getnative.me/')
res.body.to_s
=> ""

res = Typhoeus.get('https://getnative.me/')
res.body.to_s
=> <!doctype html>\n<html>\n   <head>\n      <meta charset=\"utf-8\">...

```

**Comment by ixti** [comment]
This is a known issue that was fixed in master. You can use release [5.0.0.pre](https://rubygems.org/gems/http/versions/5.0.0.pre) that includes the fix.

See: #489, #433, #422 and #508
