### ISSUE TITLE
Form-encoded nil attributes formatting incorrectly

### ISSUE THREAD

**Issue by mgomes** [httprb/http#539]
When attempting to POST with form-encoded params, I get an invalid format for parameters that have a `nil` value.

Given this request:

```ruby
attributes = { name: 'John', phone: nil, source: 'web' }

req = HTTP.timeout(connect: 15, read: 30)
req.post('uri', form: attributes)
```

I would expect the following form-encoded body:

```
name=John&phone=&source=web
```

However the `phone` parameter comes in incorrectly:

```
name=John&phone&source=web
```

Using `HTTP::URI.form_encode` though, generates the correct parameters:

```ruby
2.6.1 :004 > attributes = { name: 'John', phone: nil, source: 'web' }
 => {:name=>"John", :phone=>nil, :source=>"web"} 
2.6.1 :005 > HTTP::URI.form_encode(attributes)
 => "name=John&phone=&source=web"
```

**Comment by ixti** [comment]
`:form` uses different method of params encoding:

https://github.com/httprb/form_data

It defaults to stdlib's `URI.encode_www_form`:

``` ruby
URI.encode_www_form("a" => "b", "c" => nil, "d" => "e")
# => "a=b&c&d=e"
```

You can swap form data's encoder though:

``` ruby
HTTP::FormData::Urlencoded.encoder = HTTP::URI.method(:form_encode)
```

Notice though that both variants: `"a=b&c&d=e"` and `"a=b&c=&d=e"` are totally valid.

**Comment by mgomes** [comment]
Thanks @ixti.
