### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by duybn-0885** [httprb/http#553]
I am trying to send a HTTP Request like that "(https://api.opencagedata.com/geocode/v1/json?q=199%20Trần%20Quốc%20Hoàn,%20Phường%20Mai%20Dịch,%20Quận%20Cầu%20Giấy,%20Thành%20phố%20Hà%20Nội&key=*********")" (key is private so i dont want to public here)

But i only get response is `unexpected token at '<html><body><h1>400 Bad request</h1> Your browser sent an invalid request. </body></html> '`
I think I have some problems with URL of the request but i can't find solution for it. Please give me some solutions for it

**Comment by mikegee** [comment]
I get the same response with curl:

```
% curl 'https://api.opencagedata.com/geocode/v1/json?q=199%20Trần%20Quốc%20Hoàn,%20Phường%20Mai%20Dịch,%20Quận%20Cầu%20Giấy,%20Thành%20phố%20Hà%20Nội&key=mysecretkey'
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```
I don't think the problem is related to this gem. Maybe that server doesn't handle unicode query params?

```
% curl 'https://api.opencagedata.com/geocode/v1/json?q=myasciiquery&key=mysecretkey'
{"documentation":"https://opencagedata.com/api","licenses":[{"name":"see attribution guide","url":"https://opencagedata.com/credits"}],"results":[],"status":{"code":401,"message":"invalid API key"},"stay_informed":{"blog":"https://blog.opencagedata.com","twitter":"https://twitter.com/opencagedata"},"thanks":"For using an OpenCage Data API","timestamp":{"created_http":"Sun, 26 May 2019 20:07:18 GMT","created_unix":1558901238},"total_results":0}
```

**Comment by freyfogle** [comment]
Hi, Ed from OpenCage here. You need to URI encode the query. So should be

`q=199%20Tr%E1%BA%A7n%20Qu%E1%BB%91c%20Ho%C3%A0n%2C%20Ph%C6%B0%E1%BB%9Dng%20Mai%20D%E1%BB%8Bch%2C%20Qu%E1%BA%ADn%20C%E1%BA%A7u%20Gi%E1%BA%A5y%2C%20Th%C3%A0nh%20ph%E1%BB%91%20H%C3%A0%20N%E1%BB%99i&key=YOUR_API_KEY&pretty=1`

**Comment by ixti** [comment]
As OpenCage [API docs](https://opencagedata.com/api#forward) says:

---

![image](https://user-images.githubusercontent.com/94782/58516228-91f84800-81a7-11e9-9aa8-4318e4178bfe.png)

---

In API [best practices](https://opencagedata.com/api#bestpractices) it says:

> If you are geocoding non-English locations, please don't forget to set the optional language parameter.

**Comment by ixti** [comment]
@freyfogle :+1: :smile:

**Comment by freyfogle** [comment]
Just a quick note to say thanks for posting this issue. We have now changed our documentation to try to make the need for URL encoding more clear.

**Comment by ixti** [comment]
@freyfogle :+1:
