### ISSUE TITLE
Recommended convention for dynamically building requests?

### ISSUE THREAD

**Issue by uberllama** [httprb/http#554]
I am using outer api request POROs that define the parameters of each of the requests in my system (`GetEmployeeRequest`, `GetTokenRequest`, etc). Each of these will define 0 or more headers, form body, params, proxy, json body, etc. So the centralized request builder needs to be able to incrementally build an HTTP Request object.

Pseudo code: 

```ruby
request = HTTP::Request.new
request.url = "http://example.com
request.headers = headers unless headers.nil?
request.params = params unless params.nil?
request.via = "some proxy" proxy if proxy
request.get
```

I'd be happy to do a doc PR if there's a recommended approach to this?

**Comment by tarcieri** [comment]
These can all be defined in terms of the [Chainable](https://www.rubydoc.info/gems/http/HTTP/Chainable) module (which is called out in the README, but perhaps not prominently enough).

I believe the following will work, as passing `nil` to any of these has the same effect as not passing anything:

```ruby
HTTP.headers(headers)
    .params(params)
    .via(proxy)
    .get("http://example.com")
```

**Comment by uberllama** [comment]
>  as passing `nil` to any of these has the same effect as not passing anything:

That's the ticket right there, thanks! I was getting into using reduce to chain send. Just passing everything even if nil is much simpler. ;) Cheers.

**Comment by uberllama** [comment]
So it turns out you can't pass nil to `proxy`. I'm going to have to dynamically build this using `send`.

**Comment by tarcieri** [comment]
You can always bind to an intermediate variable:

```ruby
request = HTTP.headers(headers).params(params)
request = request.via(proxy) if proxy
request.get("http://example.com")
```
