### ISSUE TITLE
Can't get response content for some urls

### ISSUE THREAD

**Issue by killernova** [httprb/http#555]
When I request url like this one: `r = HTTP.get('https://international.la-croix.com')`, it returns the code of 200: `r.code => 200`, but when I want to print the response body, it just returns blank string: `r.to_s => ""`.

This problem only appears in some urls, and most of them works fine.

**Comment by ixti** [comment]
It's known issue with parser used in released versions:

- https://github.com/httprb/http/issues/422

You can switch to [5.0.0.pre](https://rubygems.org/gems/http/versions/5.0.0.pre) version which has required fix applied.
