### ISSUE TITLE
Backporting http parser upgrade?

### ISSUE THREAD

**Issue by zanker-stripe** [httprb/http#567]
Given https://github.com/httprb/http/pull/489/files is in 5.0, and wanting to hold 5.0 until there is more (https://github.com/httprb/http/issues/564). Is there a reason to not backport the HTTP Parser upgrade?

The changes look simple enough I don't see a reason we can't just do a 4.1.2 to unblock fixing the Upgrade issue, without having to require moving to a pre version.

I'm happy to do  the port, just checking ahead of time. I'll be going on vacation later today so I can do it when I'm back in ~10 days.

**Comment by ixti** [comment]
@zanker-stripe Sure. I guess we should release backport as minor bump though. I'll try to tackle that during next week, but I'll be fine if anybody will beat me to it. :D

**Comment by justinmichael-stripe** [comment]
Hello!  Just a friendly bump and +1 so this doesn't get lost. 🙂

**Comment by ixti** [comment]
Done (#570) and released as [v4.2.0](https://rubygems.org/gems/http/versions/4.2.0)

**Comment by jessicaspeir** [comment]
This "upgrade" appears to pull in a different gem entirely, and the http-parser gem doesn't appear to work on JRuby. We just pulled in http v4.2.0 and got this error:

> Resolving dependencies.............
Fetching rake 13.0.0
Installing rake 13.0.0
Fetching public_suffix 4.0.1
Installing public_suffix 4.0.1
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using ast 2.4.0
Using bundler 1.17.3
Fetching childprocess 3.0.0
Installing childprocess 3.0.0
Using safe_yaml 1.0.5
Using crack 0.4.3
Using diff-lcs 1.3
Using docile 1.3.2
Using unf 0.1.4 (java)
Using domain_name 0.5.20190701
Using fakefs 0.20.1
Fetching ffi 1.11.1 (java)
Installing ffi 1.11.1 (java)
Fetching ffi-compiler 1.0.1
Installing ffi-compiler 1.0.1
Using hashdiff 1.0.0
Using http-cookie 1.0.3
Using http-form_data 2.1.1
Fetching http-parser 1.2.1
Installing http-parser 1.2.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/opt/atlassian/pipelines/agent/build/.gems/gems/http-parser-1.2.1/ext
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -cp
:/root/.m2/repository/org/jruby/jruby-complete/9.2.6.0/jruby-complete-9.2.6.0.jar
org.jruby.Main -rrubygems
/opt/atlassian/pipelines/agent/build/.gems/gems/rake-13.0.0/exe/rake
RUBYARCHDIR=/opt/atlassian/pipelines/agent/build/.gems/extensions/universal-java-11/2.5.0/http-parser-1.2.1
RUBYLIBDIR=/opt/atlassian/pipelines/agent/build/.gems/extensions/universal-java-11/2.5.0/http-parser-1.2.1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper
(file:/root/.m2/repository/org/jruby/jruby-complete/9.2.6.0/jruby-complete-9.2.6.0.jar)
to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of
org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal
reflective access operations
WARNING: All illegal access operations will be denied in a future release
mkdir -p x86_64-linux/http-parser
cc -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -Wextra
-O3 -fPIC   -o x86_64-linux/http-parser/http_parser.o -c
./http-parser/http_parser.c
rake aborted!
Command failed with status (127): [cc -fexceptions -O
-fno-omit-frame-pointer...]
/opt/atlassian/pipelines/agent/build/.gems/gems/ffi-compiler-1.0.1/lib/ffi-compiler/compile_task.rb:133:in
`block in define_task!'
/opt/atlassian/pipelines/agent/build/.gems/gems/rake-13.0.0/exe/rake:27:in
`<main>'
Tasks: TOP => default => x86_64-linux/libhttp-parser-ext.so =>
x86_64-linux/http-parser/http_parser.o
(See full trace by running task with --trace)
rake failed, exit code 1
Gem files will remain installed in
/opt/atlassian/pipelines/agent/build/.gems/gems/http-parser-1.2.1 for
inspection.
Results logged to
/opt/atlassian/pipelines/agent/build/.gems/extensions/universal-java-11/2.5.0/http-parser-1.2.1/gem_make.out
An error occurred while installing http-parser (1.2.1), and Bundler cannot
continue.
Make sure that `gem install http-parser -v '1.2.1` succeeds before bundling.
In Gemfile:
  http was resolved to 4.2.0, which depends on
    http-parser

**Comment by tarcieri** [comment]
@jessicaspeir oof, that's unfortunate, and seems like a semver breakage

@ixti what do you think we should do?

**Comment by ixti** [comment]
Yes, we changed underlying http parser, but it's implementation details and should not be considered breaking change IMO. But this change is big enough that's why we bumped minor version. New parser is fully compatible and tested with JRuby (both parser and http gem are).

I believe it might be related to system gems (similar to #572).

**Comment by mikker** [comment]
The new http-parser works on the jruby images I've tried, but it needs a c compiler and rake. `apt install build-essential` or `yum install gcc` and `gem install rake` makes it compile just fine

**Comment by jessicaspeir** [comment]
Its good to know that it is working for others. I have limited knowledge of how jruby works, but it seems very odd that to install a gem with jruby I would need a C compiler. I've never encountered that before in ~4 years of development on a jruby platform.

**Comment by ixti** [comment]
@jessicaspeir previous backend had java version, so that it was compiled for java, but its development was stalled, and thus was not working correctly with `Upgrade: h2,h2c` headers. We switched to use different parser library that is written as [FFI](https://en.wikipedia.org/wiki/Foreign_function_interface) binding to underlying C HTTP parser. Naturally it requires C compiler now.

The only difference in HTTP 4.2.0 from previous version is exactly this parser change. If you prefer not to have C compiler, you may safely stay at previous version of http gem.

**Comment by jessicaspeir** [comment]
Thanks for all the help! I was able to get the build working in our Linux build container, so that's great. Unfortunately we also have a requirement to be able to build on Windows, and I'm getting the same "Failed to build native extensions" error. Any thoughts?

**Comment by ixti** [comment]
@jessicaspeir sorry took me a while to respond. Unfortunately I don't have Windows machine to reproduce, so I can't help here. Sorry.
