### ISSUE TITLE
Does this support HTTP/2?

### ISSUE THREAD

**Issue by rhymes** [httprb/http#596]
Sorry If I'm opening an issue for what is clearly a question but I couldn't find out which versions of HTTP this gem supports.

It's not wrriten either in the README, nor in the [rubygems description](https://rubygems.org/gems/http) and I couldn't find it by searching the [forum](https://groups.google.com/forum/#!forum/httprb) as well.

I assume it supports HTTP 1.0 and 1.1, but does it support HTTP/2?

Thanks!

**Comment by tarcieri** [comment]
No, it does not, and there aren’t any plans to add support.
