### ISSUE TITLE
timeout: undefined method `to_sym' for :Integer

### ISSUE THREAD

**Issue by Deepak275** [httprb/http#603]
Hi Team,
I am trying to set timeout before the doing the request. I am getting 

> /Users/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/chainable.rb:94:in `timeout': undefined method `to_sym' for 3:Integer (NoMethodError)
> Did you mean?  to_s

Here is my code snippet:

> response = HTTP.headers(params[:header]).timeout(3).get(url, body: params[:body])

Please help me with anything I am missing here

**Comment by ixti** [comment]
@Deepak275 Please update your code to run with latest stable http gem version. API of `#timeout()` was simplified in [4.0.0](https://github.com/httprb/http/blob/master/CHANGES.md#400-2018-10-15). For earlier versions you should use full-syntax, see: https://github.com/httprb/http/pull/446

**Comment by tarcieri** [comment]
Let's use #754 to track this class of errors
