### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by tarcieri** [httprb/http#633]
[Travis CI has changed their pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) and it's [no longer usable for OSS projects](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

I would suggest migrating CI to GitHub Actions.

**Comment by ixti** [comment]
@tarcieri :+1:

**Comment by tarcieri** [comment]
See also #627 for more CI problems

**Comment by tarcieri** [comment]
Here's an example template: https://github.com/postmodern/digest-crc/blob/master/.github/workflows/ruby.yml

**Comment by ixti** [comment]
@tarcieri thanks, started work on this, but ssl issues are kinda make it not ok to be merged yet ;))
