### ISSUE TITLE
Header key with underscore being converted to a dash 

### ISSUE THREAD

**Issue by kroe761** [httprb/http#641]
I am trying to create a POST request that contains the key `app_token` in the header.  My code

```
HTTP.headers({:app_token => "some-guid-token"})
         .post("https://service.mycompany.net/",
                     json: { key: "value"})
```

However, when I make my call, I am notified that app_token was not proved.  Looking at the `req` in `HTTP::Client.request`, I see that the header has been converted to `App-Token`.  This is causing my request to fail.  Is there a workaround?  We are using version 4.4.1.

**Comment by tarcieri** [comment]
Dup of: #337, #576

**Comment by kroe761** [comment]
I'm completely confused. Are you saying that my code should have resulted in 'app_token' in the request?  If not, what should I have done differently to fix my code?

**Comment by tarcieri** [comment]
There's a monkeypatch here:

https://github.com/httprb/http/issues/337#issuecomment-550412661

Otherwise #576 is a more permanent but unreleased fix.

**Comment by kroe761** [comment]
Works perfectly!  Thank you!
