### ISSUE TITLE
consider switching from http-parser to llhttp 

### ISSUE THREAD

**Issue by brodock** [httprb/http#658]
http-parser is considered unmaintained. On their repository they suggest people move to llhttp. 

There is a ruby binding for it in https://github.com/metabahn/llhttp, linked from the original project https://llhttp.org/

**Comment by brodock** [comment]
it seems this was actually done as per: https://github.com/httprb/http/pull/651, but readme still mentions http-parser

**Comment by tarcieri** [comment]
It's been merged but not released. It'd be great to get the README updated.

**Comment by tarcieri** [comment]
README updated
