### ISSUE TITLE
Release 5.0

### ISSUE THREAD

**Issue by tarcieri** [httprb/http#659]
Supersedes #564.

It'd probably be good to ship 5.0, even in the current state, for better or worse.

There will no doubt be bugs but it will at least move things forward.

**Comment by tarcieri** [comment]
Opened a PR for this: https://github.com/httprb/http/pull/660

**Comment by tarcieri** [comment]
It's out! 🎉 

https://rubygems.org/gems/http/versions/5.0.0

**Comment by jrnk** [comment]
@tarcieri first: thanks for shipping 5.0 👍  
One issue I see in the 5.0 release that wasn't in rc3: it seems like although it is mentioned in the changelog:

#593 #592 Support informational (1XX) responses. (@ixti)

That commit is missing from the release, HTTP 100 responses worked with rc3, but stopped working with this 5.0 release.

**Comment by tarcieri** [comment]
@jrnk not sure what the problem is. Can you open an issue?

**Comment by jrnk** [comment]
@tarcieri sure! The problem is that the mentioned changes that should be in the 5.0 release are not present :)
I will open an issue.
