### ISSUE TITLE
4.x add deprecation warning to response.parse()

### ISSUE THREAD

**Issue by ronald** [httprb/http#665]
In Version 5 Http.get(url).parse throws ArgumentError "wrong number of arguments (given 0, expected 1)"
https://github.com/httprb/http/blob/53b7b91ac3012dbdfb43fa65947fd8d9c2311c7c/lib/http/response.rb#L159 introduced with #538.

I suggest adding a deprecation warning in Version 4.

**Comment by tarcieri** [comment]
That's a good idea.

**Comment by ixti** [comment]
https://github.com/httprb/http/commit/fa542332fd625a26480bb8677be16c66660bd507

**Comment by DannyBen** [comment]
Actually.... I am not sure I understand why this API was changed at all? This change makes the `#parse` method much less usable. If I know what the content type is, I do not need the HTTP gem to parse it for me - I can `JSON.parse` it myself.... I was assuming that the intention of the `#parse` method is to do "best effort" to parse it.

In addition, the response object already knows what the mime type is, so why not use it to parse?

The below code feels wrong:

```ruby
require 'http'

url = "https://jsonplaceholder.typicode.com/posts/1"
response = HTTP.get url

# Why do we have to do this...
parsed_response = response.parse(response.mime_type)

# ...instead of this?
# parsed_response = response.parse

p parsed_response
```

To me, the beauty of the HTTP gem is that it "just works". 
Can't the `#parse` method be changed to have its `type` argument optional?

```ruby
def parse(type = nil)
  type ||= mime_type
  MimeType[type].decode to_s
end
```

What am I missing?

**Comment by ixti** [comment]
@DannyBen

Even if you pass `Accept: application/json` header, server might respond with plain text, or html, etc. So implicit mime type inferring from the response might lead into a confusing experience IMO:

``` ruby
HTTP.headers(:accept => "application/json").get("https://httpbin.org/html").parse
# HTTP::Error: Unknown MIME type: text/html
```

Let's say you define HTML decoder for that:

``` ruby
module HTTP
  module MimeType
    class HTML < Adapter
      def decode(str)
        ::Nokogiri::HTML str
      end
    end

    register_adapter "text/html", HTML
    register_alias   "text/html", :html
  end
end
```

And let's say you expect result to be a JSON, but it comes back as HTML (error or such):

``` ruby
payload = HTTP.headers(:accept => "application/json").get("https://httpbin.org/html").parse
```

Now you have a parsed response. But it's far from what you expect. So, to be honest I consider `parse` as a simple helper over `JSON.parse(response.to_s)`, thus I think `response.parse(:json)` (which can be enhanced to pick up the most efficient adapter) is a better choice.

**Comment by ixti** [comment]
It's easy enough to revert this API change locally:

``` ruby
module HTTP
  class Response
    module ImplicitParse
      def parse(as = mime_type)
        super(as)
      end
    end

    prepend ImplicitParse
  end
end
```

You can also overload `HTTP::Response#parse` completely.

**Comment by ronald** [comment]
Since we are already off topic, i can contribute my 2 cents.

How about if we let `parse()` be automatic again, but require an allow list to be provided.
So only if the mimetype matches the expected one, automatic parsing takes place.

```
Http.get(url).parse(:json, :xml)
```
- if response is json or xml it's parsed
- if response type anything else it throws an error

**Comment by ronald** [comment]
IMHO on-topic would have been there: #538

**Comment by DannyBen** [comment]
> IMHO on-topic would have been there: #538

A closed 2 years old topic? I doubt any reply there would have received any attention, but one thing is certain - discussing whether or not this is on topic, is by itself off topic... :)

Bottom line, your call of course how to handle this. If there is any weight to my opinion, I say either make it parse by mime type (and fail gracefully if it can't), or remove the `parse` method altogether. Any other route is awkward at best, and bad form at worst.

**Comment by tarcieri** [comment]
If you really liked `parse()` with no argument and want it back, I'd suggest opening a PR that reverts #538 and we can discuss it there.

**Comment by ixti** [comment]
I've reverted the deprecation warning in 4.x.x branch, further discussion of `#parse` future should go in #670
