### ISSUE TITLE
HTTP 5.0 no longer supports VCR

### ISSUE THREAD

**Issue by hugopassos** [httprb/http#672]
As a result of #546, requests made with [VCR](https://github.com/vcr/vcr) are now raising the error `KeyError: key not found: :request` as the parameter `request` is not sent by it:

![image](https://user-images.githubusercontent.com/22309731/120379816-ad4a4080-c2f6-11eb-884a-43fa00665dc4.png)

The error will be raised at `/lib/http/response.rb:46`

Can't it behave like an optional parameter like it was in the previous version of the gem?

**Comment by tarcieri** [comment]
It seems like for the purposes of VCR, which is trying to simulate how real-world requests behave, it should probably start passing `:request` for http.rb v5.

We could potentially allow `:request` to be omitted as a workaround, but that seems suboptimal for the specific use case of VCR, IMO.

**Comment by hugopassos** [comment]
I get your point. So maybe I should open an issue in there? Sorry I am no specialist in this matter and my first thought was to do it in here as in previous HTTP.rb versions it worked fine, and it is also working fine in other libraries

**Comment by tarcieri** [comment]
IIRC VCR uses webmock (haven't used it in awhile, sorry) so that would probably be the right place to enquire about this. There might already be a relevant issue.

**Comment by cesc1989** [comment]
👋🏽  @hugopassos this was fixed in https://github.com/bblimke/webmock/issues/940

Update webmock to 3.13.0

**Comment by tarcieri** [comment]
Awesome, thanks!

**Comment by hugopassos** [comment]
@cesc1989 thanks!
