### ISSUE TITLE
Maintain backwards compatibilty with HTTP::Response :uri

### ISSUE THREAD

**Issue by schwern** [httprb/http#677]
5.0.0 now requires HTTP::Response takes a :request. That's fine.
https://github.com/httprb/http/commit/2fb5e6f26a324864f990fef6ab4d7a4987f36dce

However, it removed accepting :uri and that broke my test factories. It's not a hard fix, but it seems unnecessary.

How about instead to maintain backwards compatibility...

* It takes a :verb which defaults to :get, just like the tests.
* :request defaults to `HTTP::Request.new( verb: opts[:verb], uri: opts[:uri] )`
* If given both a request and a uri and/or verb, that is an ArgumentError.

Make it clear in the docs that :uri and :verb are deprecated and will be removed in version 6. That will give people a bit of a buffer.

**Comment by ixti** [comment]
Agree. Resolved in #678
