### ISSUE TITLE
Do we have support for OAuth1.0 and OAuth2.0 like POSTMAN Tool?

### ISSUE THREAD

**Issue by rkhapre** [httprb/http#683]
Hi All,
Currently i see we have support for Basic Authentication with username and password.
Do we have support for OAuth1.0 and OAuth2.0 like POSTMAN Tool?
Does anyone tried or used code to support httprb?

Please let me know if this is something possible with this gem?

Thanks

**Comment by tarcieri** [comment]
There is no integrated OAuth support, no.

You need to use a 3rd party OAuth library to obtain an OAuth token, then pass it using the `Authorization` header.
