### ISSUE TITLE
Cookies extraction is not working properly in 5.x

### ISSUE THREAD

**Issue by flosacca** [httprb/http#693]
In 5.0.2, `HTTP::Response#cookies` does not return cookies set by Set-Cookie header fields in a non-canonical form (e.g. `set-cookie` rather than `Set-Cookie`). It seems due to #576. The behavior of `HTTP::Headers#each` changes to yield the original field name, but `HTTP::Response#cookies` iterates over header fields by calling `HTTP::Headers#each` and only finds fields with name exactly equal to `Set-Cookie`.

**Comment by tarcieri** [comment]
It would seem this would impact all 5.x releases, not just 5.0.2?

**Comment by tarcieri** [comment]
Thanks for confirming. Seems like an easy fix if anyone would like to open a PR.
