### ISSUE TITLE
undefined method 'wait_readable' for #<OpenSSL::SSL::SSLSocket:0x00007feb9ebacc00>

### ISSUE THREAD

**Issue by lukasz-wojcik** [httprb/http#697]
`5.0.3` version has just been released has been released. We have bumped the version of the gem  automatically since that was a patch update and then experienced a `NoMethodError` 

```
undefined method `wait_readable' for #<OpenSSL::SSL::SSLSocket:0x00007feb9ebacc00>
```
backtrace points to: `/gems/http-5.0.3/lib/http/timeout/global.rb:38`: https://github.com/httprb/http/blob/66a3af2fa68b126316c78ac90a12b88681e82728/lib/http/timeout/global.rb#L38

There is a change in that line in a following PR: https://github.com/httprb/http/pull/691

However in another place in a similar case the method `wait_readable` is  called on `io` object not directly on socket:
https://github.com/httprb/http/blob/66a3af2fa68b126316c78ac90a12b88681e82728/lib/http/timeout/global.rb#L83-L84

https://github.com/httprb/http/blob/66a3af2fa68b126316c78ac90a12b88681e82728/lib/http/timeout/global.rb#L92-L96

**Comment by tarcieri** [comment]
@lukasz-wojcik can you verify this fixes the problem? If it does, I can cut another release.
