### ISSUE TITLE
Incorrect method documentation?

### ISSUE THREAD

**Issue by joevandyk** [httprb/http#732]
https://github.com/httprb/http/blob/13ce3c2710bc27b467dda68f908149a2f69643cc/lib/http/connection.rb#L89

It says the method can return `nil` there's no more data - however, it looks like it would return an empty string when that happens?

**Comment by tarcieri** [comment]
Have a look at this line: https://github.com/httprb/http/blob/13ce3c2710bc27b467dda68f908149a2f69643cc/lib/http/connection.rb#L91

**Comment by joevandyk** [comment]
well i feel dumb now
