### ISSUE TITLE
Version 5.x bump?

### ISSUE THREAD

**Issue by mjankowski** [httprb/http#777]
Looks like most of the recent work is around an upcoming 6.x release with mix of style cleanup and dropping old rubies, etc ... any chance of getting a 5.x version bump to include the handful of changes unrelated to that effort, but merged since last release?

**Comment by ixti** [comment]
Released as 5.2.0

**Comment by ixti** [comment]
Please see 5.2.0 changelog for potentially breaking changes: https://github.com/httprb/http/blob/5-x-stable/CHANGELOG.md

**Comment by mjankowski** [comment]
Thanks!
